### ISSUE TITLE
_.flow breaks when upgrading from 3.5.0 to 3.6.0/3.7.0

### ISSUE THREAD

**Issue by felixSchl** [lodash/lodash#1164]
The following code executed well in lodash v.3.5.0,
but breaks in 3.6.0 and 3.7.0 (see below).

```javascript
var _ = require('lodash');

console.log(
    _([ { id: 'a' }
      , { id: 'b' }
      ])
        .filter(_.flow(
            _.partial(_.result, _, 'id')
          , _.partial(_.isEqual, _, 'a')
        ))
        .value()
);
```

In v.3.5.0, this would yield `[ { id: 'a' } ]`

However, in 3.6.0 and 3.7.0, it throws:
```
/[...]/node_modules/lodash/index.js:3267
            wrapper = wrapper[getFuncName(data[0])].apply(wrapper, data[3]);
                                                   ^
TypeError: Cannot read property 'apply' of undefined
    at Function.<anonymous> (/[...]/node_modules/lodash/index.js:3267:52)
    at Object.<anonymous> (/[...]/proof.js:7:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by jdalton** [comment]
Dup of #1160.
