### ISSUE TITLE
Undefined used as weak map key

### ISSUE THREAD

**Issue by BorePlusPlus** [lodash/lodash#1319]
Hi,

I am using lodash with node.js 0.12.5 and am getting following error thrown.

```
      return metaMap.get(func);
                     ^
TypeError: Invalid value used as weak map key
    at WeakMap.get (native)
    at getData (/home/bore/stuff/node_modules/lodash/index.js:3856:22)
    at isLaziable (/home/bore/stuff/node_modules/lodash/index.js:4142:18)
    at wrapper (/home/bore/stuff/node_modules/lodash/index.js:3524:17)
    at dropTableStep (/home/bore/stuff/src/event-summary.js:29:12)
    at /home/bore/stuff/node_modules/lodash/index.js:3337:35
    at arrayMap (/home/bore/stuff/node_modules/lodash/index.js:1431:25)
    at Function.map (/home/bore/stuff/node_modules/lodash/index.js:6693:14)
    ....
```

On a first glance it seems strange to use `other` as a lookup key [here](https://github.com/lodash/lodash/blob/7351c0b0b941e7faa450a7f53713659b3ebe76dc/lodash.js#L4151) as all non-lodash functions will cause it to evaluate to undefined (thus causing the error).

**Comment by jdalton** [comment]
Can you post a small repro so I can add a unit test.

**Comment by BorePlusPlus** [comment]
Sure. I can try to isolate the issue on the train home...

**Comment by BorePlusPlus** [comment]
This seems to do it:

```js
var _ = require('lodash');

function run(a, b) {
    console.log('run', arguments);
}

_.curry(run)(1);
```
produces
```
/home/bore/projects/isolated/node_modules/lodash/index.js:3856
      return metaMap.get(func);
                     ^
TypeError: Invalid value used as weak map key
    at WeakMap.get (native)
    at getData (/home/bore/projects/isolated/node_modules/lodash/index.js:3856:22)
    at isLaziable (/home/bore/projects/isolated/node_modules/lodash/index.js:4142:18)
    at wrapper (/home/bore/projects/isolated/node_modules/lodash/index.js:3524:17)
    at Object.<anonymous> (/home/bore/projects/isolated/revolver.js:7:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by jdalton** [comment]
Thanks, patched.

**Comment by BorePlusPlus** [comment]
Thanks
