### ISSUE TITLE
Issue using "_.partial" on function generated with bluebird's ".promisifyAll()"

### ISSUE THREAD

**Issue by reggi** [lodash/lodash#1369]
I'm getting a strange error when applying a partial on a promise. Not sure why this is happening. The tests below prove that it only occurs on a promise generated using bluebird's ".promisifyAll()" function.

```javascript
var Promise = require("bluebird")
var _ = require("lodash")
var mock = require('mock-fs')
var fs = Promise.promisifyAll(require("fs"))
var chai = require("chai")
var chaiAsPromised = require("chai-as-promised")
var expect = chai.expect
chai.use(chaiAsPromised)
chai.should()

mock({
  'path/hello.txt': 'file content here'
});

describe("issue using fs promisifyAll", function(){
  describe("fs.readFileAsync()", function(){
    it("should be a funciton", function(){
      expect(fs.readFileAsync).to.be.instanceof(Function)
    })
    it("should use mock-fs", function(){
      return fs.readFileAsync("path/hello.txt", "utf8").should.eventually.equal("file content here")
    })
  })
  describe("_.partial()", function(){
    it("should return function", function(){
      var readFile = _.partial(fs.readFileAsync, "path/hello.txt", "utf8")
      expect(readFile).to.be.instanceof(Function)
    })
    it("should create promise", function(){
      var readFile = _.partial(fs.readFileAsync, "path/hello.txt", "utf8")
      return readFile().should.eventually.equal("file content here")
    })
  })
})

var dummyPromise = function(){
  return Promise.resolve("file content here")
}

describe("issue using dummy promise", function(){
  describe("dummyPromise()", function(){
    it("should be a funciton", function(){
      expect(dummyPromise).to.be.instanceof(Function)
    })
    it("should use mock-fs", function(){
      return dummyPromise("path/hello.txt", "utf8").should.eventually.equal("file content here")
    })
  })
  describe("_.partial()", function(){
    it("should return function", function(){
      var readFile = _.partial(dummyPromise, "path/hello.txt", "utf8")
      expect(readFile).to.be.instanceof(Function)
    })
    it("should create promise", function(){
      var readFile = _.partial(dummyPromise, "path/hello.txt", "utf8")
      return readFile().should.eventually.equal("file content here")
    })
  })
})

var dummyCallback = function(path, encoding, cb){
  return cb(null, "file content here")
}

var dummyPromisified = Promise.promisify(dummyCallback)

describe("issue using dummy promisify", function(){
  describe("dummyPromisified()", function(){
    it("should be a funciton", function(){
      expect(dummyPromisified).to.be.instanceof(Function)
    })
    it("should use mock-fs", function(){
      return dummyPromisified("path/hello.txt", "utf8").should.eventually.equal("file content here")
    })
  })
  describe("_.partial()", function(){
    it("should return function", function(){
      var readFile = _.partial(dummyPromisified, "path/hello.txt", "utf8")
      expect(readFile).to.be.instanceof(Function)
    })
    it("should create promise", function(){
      var readFile = _.partial(dummyPromisified, "path/hello.txt", "utf8")
      return readFile().should.eventually.equal("file content here")
    })
  })
})


var lib = {}

lib.dummy = function(path, encoding, cb){
  return cb(null, "file content here")
}

Promise.promisifyAll(lib)

describe("issue using dummy promisifyAll", function(){
  describe("lib.dummyAsync()", function(){
    it("should be a funciton", function(){
      expect(lib.dummyAsync).to.be.instanceof(Function)
    })
    it("should use mock-fs", function(){
      return lib.dummyAsync("path/hello.txt", "utf8").should.eventually.equal("file content here")
    })
  })
  describe("_.partial()", function(){
    it("should return function", function(){
      var readFile = _.partial(lib.dummyAsync, "path/hello.txt", "utf8")
      expect(readFile).to.be.instanceof(Function)
    })
    it("should create promise", function(){
      var readFile = _.partial(lib.dummyAsync, "path/hello.txt", "utf8")
      return readFile().should.eventually.equal("file content here")
    })
  })
})
```

This is what mocha is returning back

```


  issue using fs promisifyAll
    fs.readFileAsync()
      ✓ should be a funciton
      ✓ should use mock-fs
    _.partial()
      ✓ should return function
      1) should create promise

  issue using dummy promise
    dummyPromise()
      ✓ should be a funciton
      ✓ should use mock-fs
    _.partial()
      ✓ should return function
      ✓ should create promise

  issue using dummy promisify
    dummyPromisified()
      ✓ should be a funciton
      ✓ should use mock-fs
    _.partial()
      ✓ should return function
      ✓ should create promise

  issue using dummy promisifyAll
    lib.dummyAsync()
      ✓ should be a funciton
      ✓ should use mock-fs
    _.partial()
      ✓ should return function
      2) should create promise


  14 passing (38ms)
  2 failing

  1) issue using fs promisifiedAll _.partial() should create promise:
     TypeError: Cannot read property 'apply' of undefined
      at Context.<anonymous> (test/lodash-fsextra-partial.js:31:14)

  2) issue using dummy promisifyAll _.partial() should create promise:
     TypeError: Cannot read property 'apply' of undefined
      at Context.<anonymous> (test/lodash-fsextra-partial.js:113:14)
```

Not sure where to place this issue in `lodash` or in `bluebird`. Thoughts?

**Comment by reggi** [comment]
Here's the stack trace for the issue.

```
TypeError: Cannot read property 'apply' of undefined
    at tryCatcher (/Users/thomas/Desktop/project/node_modules/bluebird/js/main/util.js:26:22)
    at ret (eval at <anonymous> (/Users/thomas/Desktop/project/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:11:39)
    at wrapper (/Users/thomas/Desktop/project/node_modules/lodash/index.js:3592:19)
    at Context.<anonymous> (/Users/thomas/Desktop/project/test/lodash-fsextra-partial.js:113:14)
    at callFn (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runnable.js:266:21)
    at Test.Runnable.run (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runnable.js:259:7)
    at Runner.runTest (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:390:10)
    at /Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:473:12
    at next (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:315:14)
    at /Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:325:7
    at next (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by reggi** [comment]
Here's another test to prove it's not because the error is not just happening because it's an object method.

```javascript
var libq = {}

libq.dummy = function(path, encoding){
  return Promise.resolve("file content here")
}

describe("issue using dummy lib promise", function(){
  describe("libq.dummy()", function(){
    it("should be a funciton", function(){
      expect(libq.dummy).to.be.instanceof(Function)
    })
    it("should use mock-fs", function(){
      return libq.dummy("path/hello.txt", "utf8").should.eventually.equal("file content here")
    })
  })
  describe("_.partial()", function(){
    it("should return function", function(){
      var readFile = _.partial(libq.dummy, "path/hello.txt", "utf8")
      expect(readFile).to.be.instanceof(Function)
    })
    it("should create promise", function(){
      var readFile = _.partial(libq.dummy, "path/hello.txt", "utf8")
      return readFile().should.eventually.equal("file content here")
    })
  })
})
```

**Comment by reggi** [comment]
This doesn't work either
```
var readFile = _.partial.apply(lib, [lib.dummyAsync, "path/hello.txt", "utf8"])
readFile().should.eventually.equal("file content here")
```

**Comment by jdalton** [comment]
For support questions try our [gitter room](https://gitter.im/lodash/lodash).

**Comment by reggi** [comment]
@jdalton is this a support question or a bug?

**Comment by jdalton** [comment]
Looks like a support question which is why I suggested the room.
