### ISSUE TITLE
Question: testing a mixin against lodash's tests?

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1572]
If I create a mixin that replaces an actual lodash method, for example _.range. Is there a way to easily test this mixin against the standard set of tests, or am I out of luck?

**Comment by jdalton** [comment]
The lodash unit tests support pointing it to the lodash file to test. So you could piggy back lodash in a file and point to it. Though the tests aren't included in the npm package.
```bash
node path/to/lodash/test/test.js path/to/lodash-file.js
```

**Comment by Xotic750** [comment]
Thanks, that seems to work, but I do need to check that it is using the mixin function and not the original. I did however experience this fail, which I'm sure about at present.
```
[graham@tyr lodash]$ node ./test/test.js ../lodash-x/src/lodash-x.js
test.js invoked with arguments: ["/home/graham/node-v4.1.0-linux-x64/bin/node","/home/graham/source_projects/lodash/test/test.js","../lodash-x/src/lodash-x.js"]
----------------------------------------
lodash.noConflict
----------------------------------------
 FAIL - should work with a `root` of `this`
    FAIL | OK | Died on test #1     at /home/graham/source_projects/lodash/test/test.js:13517:11
    at Object.<anonymous> (/home/graham/source_projects/lodash/test/test.js:13536:4)
    at Object.<anonymous> (/home/graham/source_projects/lodash/test/test.js:22127:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12): _.runInContext is not a function
    FAIL | OK | Expected 2 assertions, but 1 were run
----------------------------------------
    PASS: 5044  FAIL: 2  TOTAL: 5046
    Finished in 19450 milliseconds.
----------------------------------------
```

**Comment by jdalton** [comment]
You should `npm i` the repo to install its dev deps.

**Comment by Xotic750** [comment]
I tried that and still the same result.
```
[graham@tyr lodash]$ ls -a
.   bower.json          CONTRIBUTING.md  doc            .git            .gitignore  lib      lodash.js     perf       test         vendor
..  CODE_OF_CONDUCT.md  dist             .editorconfig  .gitattributes  .jscsrc     LICENSE  package.json  README.md  .travis.yml
[graham@tyr lodash]$ npm i
npm WARN optional dep failed, continuing fsevents@1.0.2
qunit-extras@1.4.4 node_modules/qunit-extras

platform@1.3.0 node_modules/platform

qunitjs@1.19.0 node_modules/qunitjs

async@1.5.0 node_modules/async

docdown@0.3.0 node_modules/docdown

requirejs@2.1.20 node_modules/requirejs

chalk@1.1.1 node_modules/chalk
├── escape-string-regexp@1.0.3
├── ansi-styles@2.1.0
├── supports-color@2.0.0
├── strip-ansi@3.0.0 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

ecstatic@1.1.3 node_modules/ecstatic
├── url-join@0.0.1
├── he@0.5.0
├── mime@1.3.4
└── minimist@1.2.0

uglify-js@2.5.0 node_modules/uglify-js
├── async@0.2.10
├── uglify-to-browserify@1.0.2
├── source-map@0.5.3
└── yargs@3.5.4 (decamelize@1.1.0, camelcase@1.2.1, window-size@0.1.0, wordwrap@0.0.2)

jquery@1.11.3 node_modules/jquery

fs-extra@0.26.0 node_modules/fs-extra
├── path-is-absolute@1.0.0
├── klaw@1.1.1
├── jsonfile@2.2.3
├── graceful-fs@4.1.2
└── rimraf@2.4.3 (glob@5.0.15)

coveralls@2.11.4 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── request@2.40.0 (forever-agent@0.5.2, aws-sign2@0.5.0, tunnel-agent@0.4.1, oauth-sign@0.3.0, stringstream@0.0.5, json-stringify-safe@5.0.1, tough-cookie@2.2.0, mime-types@1.0.2, qs@1.0.2, node-uuid@1.4.3, http-signature@0.10.1, form-data@0.1.4, hawk@1.1.1)
└── js-yaml@3.0.1 (esprima@1.0.4, argparse@0.1.16)

request@2.65.0 node_modules/request
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── tunnel-agent@0.4.1
├── oauth-sign@0.8.0
├── form-data@1.0.0-rc3
├── caseless@0.11.0
├── stringstream@0.0.5
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── tough-cookie@2.2.0
├── node-uuid@1.4.3
├── qs@5.2.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.7 (mime-db@1.19.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, ctype@0.5.3, asn1@0.1.11)
├── hawk@3.1.0 (cryptiles@2.0.5, boom@2.10.0, sntp@1.0.9, hoek@2.16.3)
├── bl@1.0.0 (readable-stream@2.0.3)
└── har-validator@2.0.2 (pinkie-promise@1.0.0, commander@2.9.0, is-my-json-valid@2.12.2)

curl-amd@0.8.12 node_modules/curl-amd

istanbul@0.4.0 node_modules/istanbul
├── abbrev@1.0.7
├── wordwrap@1.0.0
├── nopt@3.0.4
├── esprima@2.5.0
├── supports-color@3.1.2 (has-flag@1.0.0)
├── once@1.3.2 (wrappy@1.0.1)
├── which@1.2.0 (is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fileset@0.2.1 (glob@5.0.15, minimatch@2.0.10)
├── resolve@1.1.6
├── escodegen@1.7.0 (estraverse@1.9.3, esutils@2.0.2, esprima@1.2.5, optionator@0.5.0, source-map@0.2.0)
├── js-yaml@3.4.3 (esprima@2.7.0, argparse@1.0.3)
└── handlebars@4.0.3 (source-map@0.4.4, optimist@0.6.1, uglify-js@2.4.24)

lodash@3.10.1 node_modules/lodash

webpack@1.12.2 node_modules/webpack
├── interpret@0.6.6
├── tapable@0.1.9
├── clone@1.0.2
├── memory-fs@0.2.0
├── esprima@2.7.0
├── supports-color@3.1.2 (has-flag@1.0.0)
├── enhanced-resolve@0.9.1 (graceful-fs@4.1.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── webpack-core@0.6.7 (source-map@0.4.4, source-list-map@0.1.5)
├── uglify-js@2.4.24 (async@0.2.10, uglify-to-browserify@1.0.2, yargs@3.5.4, source-map@0.1.34)
├── watchpack@0.2.9 (graceful-fs@4.1.2, async@0.9.2, chokidar@1.2.0)
└── node-libs-browser@0.5.3 (https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, path-browserify@0.0.0, punycode@1.3.2, string_decoder@0.10.31, os-browserify@0.1.2, process@0.11.2, domain-browser@1.1.4, assert@1.3.0, querystring-es3@0.2.1, timers-browserify@1.4.1, events@1.1.0, stream-browserify@1.0.0, vm-browserify@0.0.4, util@0.10.3, console-browserify@1.1.0, readable-stream@1.1.13, url@0.10.3, http-browserify@1.7.0, buffer@3.5.1, browserify-zlib@0.1.4, crypto-browserify@3.2.8)

sauce-tunnel@2.2.3 node_modules/sauce-tunnel
├── split@0.3.3 (through@2.3.8)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
└── request@2.21.0 (tunnel-agent@0.3.0, aws-sign@0.3.0, forever-agent@0.5.2, qs@0.6.6, json-stringify-safe@4.0.0, oauth-sign@0.3.0, mime@1.2.11, cookie-jar@0.3.0, node-uuid@1.4.3, http-signature@0.9.11, form-data@0.0.8, hawk@0.13.1)

dojo@1.10.4 node_modules/dojo

jscs@2.4.0 node_modules/jscs
├── reserved-words@0.1.1
├── natural-compare@1.2.2
├── estraverse@4.1.1
├── strip-json-comments@1.0.4
├── vow@0.4.11
├── pathval@0.1.1
├── esprima@2.5.0
├── to-single-quotes@1.0.4 (get-stdin@3.0.2)
├── to-double-quotes@1.0.2 (get-stdin@3.0.2)
├── exit@0.1.2
├── xmlbuilder@2.6.5
├── strip-bom@2.0.0 (is-utf8@0.2.0)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── cli-table@0.3.1 (colors@1.0.3)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── vow-fs@0.3.4 (vow-queue@0.4.2, node-uuid@1.4.3, glob@4.5.3)
├── babel-jscs@2.0.5 (lodash.assign@3.2.0)
├── jscs-jsdoc@1.2.0 (comment-parser@0.3.0, jsdoctypeparser@1.2.0)
├── resolve@1.1.6
├── js-yaml@3.4.3 (esprima@2.7.0, argparse@1.0.3)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.8.3, utile@0.2.1)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
├── jsonlint@1.6.2 (nomnom@1.8.1, JSV@4.0.2)
├── escope@3.2.0 (esrecurse@3.1.1, estraverse@3.1.0, es6-map@0.1.2, es6-weak-map@0.1.4)
└── babel-core@5.8.29 (try-resolve@1.0.1, slash@1.0.0, babel-plugin-remove-console@1.0.1, babel-plugin-react-display-name@1.0.3, babel-plugin-property-literals@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-constant-folding@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-react-constant-elements@1.0.3, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-undefined-to-void@1.1.6, babel-plugin-eval@1.0.1, shebang-regex@1.0.0, to-fast-properties@1.0.1, path-exists@1.0.0, trim-right@1.0.1, babel-plugin-member-expression-literals@1.0.1, babel-plugin-proto-to-assign@1.0.4, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, babel-plugin-runtime@1.0.7, globals@6.4.1, private@0.1.6, esutils@2.0.2, convert-source-map@1.1.1, js-tokens@1.0.1, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, line-numbers@0.2.0, source-map@0.5.3, babylon@5.8.29, debug@2.2.0, detect-indent@3.0.1, is-integer@1.0.6, repeating@1.1.3, bluebird@2.10.2, output-file-sync@1.1.1, regexpu@1.3.0, source-map-support@0.2.10, json5@0.4.0, core-js@1.2.3, regenerator@0.8.40)
[graham@tyr lodash]$ ls -a
.   bower.json          CONTRIBUTING.md  doc            .git            .gitignore  lib      lodash.js     package.json  README.md  .travis.yml
..  CODE_OF_CONDUCT.md  dist             .editorconfig  .gitattributes  .jscsrc     LICENSE  node_modules  perf          test       vendor
[graham@tyr lodash]$ node ./test/test.js ../lodash-x/src/lodash-x.js
test.js invoked with arguments: ["/home/graham/node-v4.1.0-linux-x64/bin/node","/home/graham/source_projects/lodash/test/test.js","../lodash-x/src/lodash-x.js"]
----------------------------------------
lodash.noConflict
----------------------------------------
 FAIL - should work with a `root` of `this`
    FAIL | OK | Died on test #1     at /home/graham/source_projects/lodash/test/test.js:13517:11
    at Object.<anonymous> (/home/graham/source_projects/lodash/test/test.js:13536:4)
    at Object.<anonymous> (/home/graham/source_projects/lodash/test/test.js:22127:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12): OriginalLodash.runInContext is not a function
    FAIL | OK | Expected 2 assertions, but 1 were run
----------------------------------------
    PASS: 5044  FAIL: 2  TOTAL: 5046
    Finished in 15700 milliseconds.
----------------------------------------
```

**Comment by jdalton** [comment]
Well, kinda but no more:
> Error: Cannot find module '../node_modules/lodash/index.js'

**Comment by Xotic750** [comment]
No, not getting that error error any more. Just to clarify, my project was also npm i'd. Is there something else that I should be doing, or is it just not going to work?
