### ISSUE TITLE
Per-method npm packages have incorrect source URLs

### ISSUE THREAD

**Issue by DannyNemer** [lodash/lodash#1774]
**EDIT:** I found the [problem](https://github.com/lodash/lodash/issues/1774#issuecomment-171375526).

The following `lodash.isequal` installation is failing. I am posting here, instead of the `npm` repo, because I believe this is a `lodash` issue.

The error below reports not finding [`lodash._stack@4.0.0`](https://www.npmjs.com/package/lodash._stack) despite the package existing on `npm`. I suspect there is a problem, however, because there have been **0 downloads** for `lodash._stack@4.0.0`:
<img width="280" alt="lodash._stack download stats" src="https://cloud.githubusercontent.com/assets/170023/12301728/96f9d504-b9ef-11e5-9a9e-e778a601815c.png">

Thank you!

Command: `npm install lodash.isequal`

Output:
```shell
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "lodash.isequal"
npm ERR! node v0.12.9
npm ERR! npm  v3.5.3

npm ERR! No compatible version found: lodash._stack@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.0.0
```

npm-debug.log:
```shell
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'lodash.isequal' ]
2 info using npm@3.5.3
3 info using node@v0.12.9
4 verbose node symlink /usr/local/bin/node
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData lodash.isequal
9 silly fetchNamedPackageData lodash.isequal
10 silly mapToRegistry name lodash.isequal
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/lodash.isequal
14 verbose request uri https://registry.npmjs.org/lodash.isequal
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:07:06
17 verbose request id ae91c80f6eff294f
18 http request GET https://registry.npmjs.org/lodash.isequal
19 http 200 https://registry.npmjs.org/lodash.isequal
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"8110X3IODAB2JFIJCM39RKRIY"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '23060',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 13 Jan 2016 17:07:06 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-dfw1821-DFW',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1452704826.806231,VS0,VE47',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"8110X3IODAB2JFIJCM39RKRIY"',
21 silly get     'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '23060',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 13 Jan 2016 17:07:06 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-dfw1821-DFW',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1452704826.806231,VS0,VE47',
21 silly get     vary: 'Accept' } ]
22 verbose get saving lodash.isequal to /Users/Danny/.npm/registry.npmjs.org/lodash.isequal/.cache.json
23 verbose makeDirectory /Users/Danny/.npm creation not in flight; initializing
24 silly makeDirectory /Users/Danny/.npm uid: 501 gid: 20
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule lodash.isequal@4.0.0 checking installable status
38 silly cache add args [ 'lodash.isequal', null ]
39 verbose cache add spec lodash.isequal
40 silly cache add parsed spec { raw: 'lodash.isequal',
40 silly cache add   scope: null,
40 silly cache add   name: 'lodash.isequal',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: 'latest',
40 silly cache add   type: 'tag' }
41 silly addNamed lodash.isequal@latest
42 verbose addNamed "latest" is being treated as a dist-tag for lodash.isequal
43 info addNameTag [ 'lodash.isequal', 'latest' ]
44 silly mapToRegistry name lodash.isequal
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/lodash.isequal
48 verbose addNameTag registry:https://registry.npmjs.org/lodash.isequal not in flight; fetching
49 verbose get https://registry.npmjs.org/lodash.isequal not expired, no request
50 silly addNameTag next cb for lodash.isequal with tag latest
51 silly addNamed lodash.isequal@4.0.0
52 verbose addNamed "4.0.0" is a plain semver version for lodash.isequal
53 silly mapToRegistry name lodash.isequal
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry uri https://registry.npmjs.org/lodash.isequal
57 verbose addRemoteTarball https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.0.0.tgz not in flight; adding
58 verbose addRemoteTarball [ 'https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.0.0.tgz',
58 verbose addRemoteTarball   'b16b56462b1b9bc24b4827aad9e6c8896553546c' ]
59 info retry fetch attempt 1 at 12:07:07
60 info attempt registry request try #1 at 12:07:07
61 http fetch GET https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.0.0.tgz
62 http fetch 200 https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.0.0.tgz
63 silly fetchAndShaCheck shasum b16b56462b1b9bc24b4827aad9e6c8896553546c
64 verbose addTmpTarball /var/folders/zd/mpj1dbdd5x13f6wrlfpfpbkm0000gn/T/npm-4325-b4fd9501/registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.0.0.tgz not in flight; adding
65 verbose addTmpTarball already have metadata; skipping unpack for lodash.isequal@4.0.0
66 silly cache afterAdd lodash.isequal@4.0.0
67 verbose afterAdd /Users/Danny/.npm/lodash.isequal/4.0.0/package/package.json not in flight; writing
68 verbose afterAdd /Users/Danny/.npm/lodash.isequal/4.0.0/package/package.json written
69 silly fetchNamedPackageData lodash._baseisequal
70 silly mapToRegistry name lodash._baseisequal
71 silly mapToRegistry using default registry
72 silly mapToRegistry registry https://registry.npmjs.org/
73 silly mapToRegistry uri https://registry.npmjs.org/lodash._baseisequal
74 verbose request uri https://registry.npmjs.org/lodash._baseisequal
75 verbose request no auth needed
76 info attempt registry request try #1 at 12:07:07
77 http request GET https://registry.npmjs.org/lodash._baseisequal
78 http 200 https://registry.npmjs.org/lodash._baseisequal
79 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
79 verbose headers   etag: '"69TCDWJIMHDT8CS7FV6LT7ROI"',
79 verbose headers   'content-type': 'application/json',
79 verbose headers   'cache-control': 'max-age=300',
79 verbose headers   'content-length': '28654',
79 verbose headers   'accept-ranges': 'bytes',
79 verbose headers   date: 'Wed, 13 Jan 2016 17:07:07 GMT',
79 verbose headers   via: '1.1 varnish',
79 verbose headers   age: '259',
79 verbose headers   connection: 'keep-alive',
79 verbose headers   'x-served-by': 'cache-dfw1831-DFW',
79 verbose headers   'x-cache': 'HIT',
79 verbose headers   'x-cache-hits': '1',
79 verbose headers   'x-timer': 'S1452704827.525768,VS0,VE0',
79 verbose headers   vary: 'Accept' }
80 silly get cb [ 200,
80 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
80 silly get     etag: '"69TCDWJIMHDT8CS7FV6LT7ROI"',
80 silly get     'content-type': 'application/json',
80 silly get     'cache-control': 'max-age=300',
80 silly get     'content-length': '28654',
80 silly get     'accept-ranges': 'bytes',
80 silly get     date: 'Wed, 13 Jan 2016 17:07:07 GMT',
80 silly get     via: '1.1 varnish',
80 silly get     age: '259',
80 silly get     connection: 'keep-alive',
80 silly get     'x-served-by': 'cache-dfw1831-DFW',
80 silly get     'x-cache': 'HIT',
80 silly get     'x-cache-hits': '1',
80 silly get     'x-timer': 'S1452704827.525768,VS0,VE0',
80 silly get     vary: 'Accept' } ]
81 verbose get saving lodash._baseisequal to /Users/Danny/.npm/registry.npmjs.org/lodash._baseisequal/.cache.json
82 silly resolveWithNewModule lodash._baseisequal@4.0.0 checking installable status
83 silly cache add args [ 'lodash._baseisequal@^4.0.0', null ]
84 verbose cache add spec lodash._baseisequal@^4.0.0
85 silly cache add parsed spec { raw: 'lodash._baseisequal@^4.0.0',
85 silly cache add   scope: null,
85 silly cache add   name: 'lodash._baseisequal',
85 silly cache add   rawSpec: '^4.0.0',
85 silly cache add   spec: '>=4.0.0 <5.0.0',
85 silly cache add   type: 'range' }
86 silly addNamed lodash._baseisequal@>=4.0.0 <5.0.0
87 verbose addNamed ">=4.0.0 <5.0.0" is a valid semver range for lodash._baseisequal
88 silly addNameRange { name: 'lodash._baseisequal',
88 silly addNameRange   range: '>=4.0.0 <5.0.0',
88 silly addNameRange   hasData: false }
89 silly mapToRegistry name lodash._baseisequal
90 silly mapToRegistry using default registry
91 silly mapToRegistry registry https://registry.npmjs.org/
92 silly mapToRegistry uri https://registry.npmjs.org/lodash._baseisequal
93 verbose addNameRange registry:https://registry.npmjs.org/lodash._baseisequal not in flight; fetching
94 verbose get https://registry.npmjs.org/lodash._baseisequal not expired, no request
95 silly addNameRange number 2 { name: 'lodash._baseisequal',
95 silly addNameRange   range: '>=4.0.0 <5.0.0',
95 silly addNameRange   hasData: true }
96 silly addNameRange versions [ 'lodash._baseisequal',
96 silly addNameRange   [ '2.0.0',
96 silly addNameRange     '2.1.0',
96 silly addNameRange     '2.2.0',
96 silly addNameRange     '2.2.1',
96 silly addNameRange     '2.3.0',
96 silly addNameRange     '2.4.0',
96 silly addNameRange     '2.4.1',
96 silly addNameRange     '3.0.0',
96 silly addNameRange     '3.0.1',
96 silly addNameRange     '3.0.2',
96 silly addNameRange     '3.0.3',
96 silly addNameRange     '3.0.4',
96 silly addNameRange     '3.0.5',
96 silly addNameRange     '3.0.6',
96 silly addNameRange     '3.0.7',
96 silly addNameRange     '4.0.0' ] ]
97 silly addNamed lodash._baseisequal@4.0.0
98 verbose addNamed "4.0.0" is a plain semver version for lodash._baseisequal
99 silly mapToRegistry name lodash._baseisequal
100 silly mapToRegistry using default registry
101 silly mapToRegistry registry https://registry.npmjs.org/
102 silly mapToRegistry uri https://registry.npmjs.org/lodash._baseisequal
103 verbose addRemoteTarball https://registry.npmjs.org/lodash._baseisequal/-/lodash._baseisequal-4.0.0.tgz not in flight; adding
104 verbose addRemoteTarball [ 'https://registry.npmjs.org/lodash._baseisequal/-/lodash._baseisequal-4.0.0.tgz',
104 verbose addRemoteTarball   'a5984200406bfdfc8ca86b1d206dd6c0520faeb5' ]
105 info retry fetch attempt 1 at 12:07:07
106 info attempt registry request try #1 at 12:07:07
107 http fetch GET https://registry.npmjs.org/lodash._baseisequal/-/lodash._baseisequal-4.0.0.tgz
108 http fetch 200 https://registry.npmjs.org/lodash._baseisequal/-/lodash._baseisequal-4.0.0.tgz
109 silly fetchAndShaCheck shasum a5984200406bfdfc8ca86b1d206dd6c0520faeb5
110 verbose addTmpTarball /var/folders/zd/mpj1dbdd5x13f6wrlfpfpbkm0000gn/T/npm-4325-b4fd9501/registry.npmjs.org/lodash._baseisequal/-/lodash._baseisequal-4.0.0.tgz not in flight; adding
111 verbose addTmpTarball already have metadata; skipping unpack for lodash._baseisequal@4.0.0
112 silly cache afterAdd lodash._baseisequal@4.0.0
113 verbose afterAdd /Users/Danny/.npm/lodash._baseisequal/4.0.0/package/package.json not in flight; writing
114 verbose afterAdd /Users/Danny/.npm/lodash._baseisequal/4.0.0/package/package.json written
115 silly fetchNamedPackageData lodash._stack
116 silly mapToRegistry name lodash._stack
117 silly mapToRegistry using default registry
118 silly mapToRegistry registry https://registry.npmjs.org/
119 silly mapToRegistry uri https://registry.npmjs.org/lodash._stack
120 silly fetchNamedPackageData lodash.keys
121 silly mapToRegistry name lodash.keys
122 silly mapToRegistry using default registry
123 silly mapToRegistry registry https://registry.npmjs.org/
124 silly mapToRegistry uri https://registry.npmjs.org/lodash.keys
125 verbose request uri https://registry.npmjs.org/lodash._stack
126 verbose request no auth needed
127 info attempt registry request try #1 at 12:07:08
128 http request GET https://registry.npmjs.org/lodash._stack
129 verbose request uri https://registry.npmjs.org/lodash.keys
130 verbose request no auth needed
131 info attempt registry request try #1 at 12:07:08
132 http request GET https://registry.npmjs.org/lodash.keys
133 http 200 https://registry.npmjs.org/lodash._stack
134 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
134 verbose headers   etag: '"EA5K2CNU1I0O9WDKB3B350GQW"',
134 verbose headers   'content-type': 'application/json',
134 verbose headers   'cache-control': 'max-age=300',
134 verbose headers   'content-length': '2897',
134 verbose headers   'accept-ranges': 'bytes',
134 verbose headers   date: 'Wed, 13 Jan 2016 17:07:08 GMT',
134 verbose headers   via: '1.1 varnish',
134 verbose headers   age: '203',
134 verbose headers   connection: 'keep-alive',
134 verbose headers   'x-served-by': 'cache-dfw1828-DFW',
134 verbose headers   'x-cache': 'HIT',
134 verbose headers   'x-cache-hits': '2',
134 verbose headers   'x-timer': 'S1452704828.097040,VS0,VE0',
134 verbose headers   vary: 'Accept' }
135 silly get cb [ 200,
135 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
135 silly get     etag: '"EA5K2CNU1I0O9WDKB3B350GQW"',
135 silly get     'content-type': 'application/json',
135 silly get     'cache-control': 'max-age=300',
135 silly get     'content-length': '2897',
135 silly get     'accept-ranges': 'bytes',
135 silly get     date: 'Wed, 13 Jan 2016 17:07:08 GMT',
135 silly get     via: '1.1 varnish',
135 silly get     age: '203',
135 silly get     connection: 'keep-alive',
135 silly get     'x-served-by': 'cache-dfw1828-DFW',
135 silly get     'x-cache': 'HIT',
135 silly get     'x-cache-hits': '2',
135 silly get     'x-timer': 'S1452704828.097040,VS0,VE0',
135 silly get     vary: 'Accept' } ]
136 verbose get saving lodash._stack to /Users/Danny/.npm/registry.npmjs.org/lodash._stack/.cache.json
137 silly fetchPackageMetaData Error: No compatible version found: lodash._stack@^3.0.0
137 silly fetchPackageMetaData Valid install targets:
137 silly fetchPackageMetaData 4.0.0
137 silly fetchPackageMetaData
137 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
137 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
137 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
137 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
137 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
137 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:95:15)
137 silly fetchPackageMetaData  error for lodash._stack@^3.0.0 [Error: No compatible version found: lodash._stack@^3.0.0
137 silly fetchPackageMetaData Valid install targets:
137 silly fetchPackageMetaData 4.0.0
137 silly fetchPackageMetaData ]
138 http 200 https://registry.npmjs.org/lodash.keys
139 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
139 verbose headers   etag: '"5M33UGOMKHDS3FGM2G024J8SJ"',
139 verbose headers   'content-type': 'application/json',
139 verbose headers   'cache-control': 'max-age=300',
139 verbose headers   'content-length': '33887',
139 verbose headers   'accept-ranges': 'bytes',
139 verbose headers   date: 'Wed, 13 Jan 2016 17:07:08 GMT',
139 verbose headers   via: '1.1 varnish',
139 verbose headers   age: '187',
139 verbose headers   connection: 'keep-alive',
139 verbose headers   'x-served-by': 'cache-dfw1829-DFW',
139 verbose headers   'x-cache': 'HIT',
139 verbose headers   'x-cache-hits': '269',
139 verbose headers   'x-timer': 'S1452704828.077647,VS0,VE0',
139 verbose headers   vary: 'Accept' }
140 silly get cb [ 200,
140 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
140 silly get     etag: '"5M33UGOMKHDS3FGM2G024J8SJ"',
140 silly get     'content-type': 'application/json',
140 silly get     'cache-control': 'max-age=300',
140 silly get     'content-length': '33887',
140 silly get     'accept-ranges': 'bytes',
140 silly get     date: 'Wed, 13 Jan 2016 17:07:08 GMT',
140 silly get     via: '1.1 varnish',
140 silly get     age: '187',
140 silly get     connection: 'keep-alive',
140 silly get     'x-served-by': 'cache-dfw1829-DFW',
140 silly get     'x-cache': 'HIT',
140 silly get     'x-cache-hits': '269',
140 silly get     'x-timer': 'S1452704828.077647,VS0,VE0',
140 silly get     vary: 'Accept' } ]
141 verbose get saving lodash.keys to /Users/Danny/.npm/registry.npmjs.org/lodash.keys/.cache.json
142 silly resolveWithNewModule lodash.keys@4.0.0 checking installable status
143 silly cache add args [ 'lodash.keys@^4.0.0', null ]
144 verbose cache add spec lodash.keys@^4.0.0
145 silly cache add parsed spec { raw: 'lodash.keys@^4.0.0',
145 silly cache add   scope: null,
145 silly cache add   name: 'lodash.keys',
145 silly cache add   rawSpec: '^4.0.0',
145 silly cache add   spec: '>=4.0.0 <5.0.0',
145 silly cache add   type: 'range' }
146 silly addNamed lodash.keys@>=4.0.0 <5.0.0
147 verbose addNamed ">=4.0.0 <5.0.0" is a valid semver range for lodash.keys
148 silly addNameRange { name: 'lodash.keys', range: '>=4.0.0 <5.0.0', hasData: false }
149 silly mapToRegistry name lodash.keys
150 silly mapToRegistry using default registry
151 silly mapToRegistry registry https://registry.npmjs.org/
152 silly mapToRegistry uri https://registry.npmjs.org/lodash.keys
153 verbose addNameRange registry:https://registry.npmjs.org/lodash.keys not in flight; fetching
154 verbose get https://registry.npmjs.org/lodash.keys not expired, no request
155 silly addNameRange number 2 { name: 'lodash.keys', range: '>=4.0.0 <5.0.0', hasData: true }
156 silly addNameRange versions [ 'lodash.keys',
156 silly addNameRange   [ '2.0.0',
156 silly addNameRange     '2.1.0',
156 silly addNameRange     '2.2.0',
156 silly addNameRange     '2.2.1',
156 silly addNameRange     '2.3.0',
156 silly addNameRange     '2.4.0',
156 silly addNameRange     '2.4.1',
156 silly addNameRange     '3.0.0',
156 silly addNameRange     '3.0.1',
156 silly addNameRange     '3.0.2',
156 silly addNameRange     '3.0.3',
156 silly addNameRange     '3.0.4',
156 silly addNameRange     '3.0.5',
156 silly addNameRange     '3.0.6',
156 silly addNameRange     '3.0.7',
156 silly addNameRange     '3.1.0',
156 silly addNameRange     '3.1.1',
156 silly addNameRange     '3.1.2',
156 silly addNameRange     '4.0.0' ] ]
157 silly addNamed lodash.keys@4.0.0
158 verbose addNamed "4.0.0" is a plain semver version for lodash.keys
159 silly mapToRegistry name lodash.keys
160 silly mapToRegistry using default registry
161 silly mapToRegistry registry https://registry.npmjs.org/
162 silly mapToRegistry uri https://registry.npmjs.org/lodash.keys
163 verbose addRemoteTarball https://registry.npmjs.org/lodash.keys/-/lodash.keys-4.0.0.tgz not in flight; adding
164 verbose addRemoteTarball [ 'https://registry.npmjs.org/lodash.keys/-/lodash.keys-4.0.0.tgz',
164 verbose addRemoteTarball   '32cb6c0691cbc5ca4b4009992d2c6076bfb98cba' ]
165 info retry fetch attempt 1 at 12:07:08
166 info attempt registry request try #1 at 12:07:08
167 http fetch GET https://registry.npmjs.org/lodash.keys/-/lodash.keys-4.0.0.tgz
168 http fetch 200 https://registry.npmjs.org/lodash.keys/-/lodash.keys-4.0.0.tgz
169 silly fetchAndShaCheck shasum 32cb6c0691cbc5ca4b4009992d2c6076bfb98cba
170 verbose addTmpTarball /var/folders/zd/mpj1dbdd5x13f6wrlfpfpbkm0000gn/T/npm-4325-b4fd9501/registry.npmjs.org/lodash.keys/-/lodash.keys-4.0.0.tgz not in flight; adding
171 verbose addTmpTarball already have metadata; skipping unpack for lodash.keys@4.0.0
172 silly cache afterAdd lodash.keys@4.0.0
173 verbose afterAdd /Users/Danny/.npm/lodash.keys/4.0.0/package/package.json not in flight; writing
174 verbose afterAdd /Users/Danny/.npm/lodash.keys/4.0.0/package/package.json written
175 silly rollbackFailedOptional Starting
176 silly rollbackFailedOptional Finishing
177 silly runTopLevelLifecycles Starting
178 silly runTopLevelLifecycles Finishing
179 silly install printInstalled
180 verbose stack Error: No compatible version found: lodash._stack@^3.0.0
180 verbose stack Valid install targets:
180 verbose stack 4.0.0
180 verbose stack
180 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
180 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
180 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
180 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
180 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
180 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
181 verbose cwd /Users/Danny/test
182 error Darwin 15.2.0
183 error argv "node" "/usr/local/bin/npm" "install" "lodash.isequal"
184 error node v0.12.9
185 error npm  v3.5.3
186 error No compatible version found: lodash._stack@^3.0.0
186 error Valid install targets:
186 error 4.0.0
187 error If you need help, you may report this error at:
187 error     <https://github.com/npm/npm/issues>
188 verbose exit [ 1, true ]
```

**Comment by DannyNemer** [comment]
Found it! The lodash npm-modules have incorrect package source URLs. For example, the package source for [`lodash.isequal`](https://www.npmjs.com/package/lodash.isequal) incorrectly links to
[`https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isequal`](https://github.com/lodash/lodash/blob/4.0.0-npm-packages/lodash.isequal)
 But it should link to
[`https://github.com/lodash/lodash/blob/npm-packages/lodash.isequal`](https://github.com/lodash/lodash/blob/npm-packages/lodash.isequal)

**Comment by jdalton** [comment]
The source urls are correct. I haven't tagged them yet so the links haven't lit up yet.
The other issue of package versions is related to #1760.

**Comment by DannyNemer** [comment]
Woops. Thank you for your help and quick response!
