### ISSUE TITLE
Cannot find module '../lib/fp/convert.js' when running npm test in v4.0.0

### ISSUE THREAD

**Issue by TheAlphaNerd** [lodash/lodash#1841]
Just noticed this was happening when lodash v4.0.0 blew up citgm (node smoke testing)

To reproduce

```
git clone git@github.com:lodash/lodash.git
cd lodash
npm install
npm test
```

```
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/fp/convert.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/thealphanerd/code/lodash/test/test-fp.js:47:28)
    at Object.<anonymous> (/Users/thealphanerd/code/lodash/test/test-fp.js:931:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by thefourtheye** [comment]
> git clone the repo

You meant the `citgm` repo, right?

**Comment by TheAlphaNerd** [comment]
no the lodash repo

**Comment by jdalton** [comment]
No worries. Our edge master branch is in flux. It'll be fixed soon enough.

**Comment by TheAlphaNerd** [comment]
@jdalton this problem appears to be in the release tarball of v4.0.0 

Thanks for taking a look

**Comment by jdalton** [comment]
Yep, I fixed it shortly after, prolly forgot to refresh the tag. I'll get to it tonight

**Comment by TheAlphaNerd** [comment]
wonderful!
