### ISSUE TITLE
lodash-cli version 4.0.0 fails to build anything, errors out

### ISSUE THREAD

**Issue by btipling** [lodash/lodash#1844]
On ubuntu 14. Installed with `npm i lodash-cli --save-dev`

Error:
```
vagrant@default-ubuntu-1404:/MW$ ./node_modules/.bin/lodash -o wut.js
evalmachine.<anonymous>:1
module.exports = require('./lodash.js');
^

ReferenceError: module is not defined
    at evalmachine.<anonymous>:1:1
    at Object.exports.runInContext (vm.js:44:17)
    at /MW/node_modules/lodash-cli/bin/lodash:3056:10
    at build (/MW/node_modules/lodash-cli/bin/lodash:3058:6)
    at Object.<anonymous> (/MW/node_modules/lodash-cli/bin/lodash:3410:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
```

After reverting to 3.10.1 I could build again.

**Comment by jdalton** [comment]
Dup of https://github.com/lodash/lodash-cli/issues/78.
