### ISSUE TITLE
iterable.length has been deprecated

### ISSUE THREAD

**Issue by snowell** [lodash/lodash#2084]
Getting a very large and obtrusive warning printed to the development console in Chrome that appears to be coming from _.forEach. Sure, it's just a warning, but it's really getting in the way of seeing my debug output. I'm running a node.js application with React, Redux, RxJs, Babel, Webpack, and probably others I'm missing. This would hopefully be an easy fix regardless of other libraries though.

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at List.Object.defineProperty.get (http://localhost:3000/my-react-app.js:61829:22)
    at http://localhost:3000/my-react-app.js:28876:33
    at Function.forEach (http://localhost:3000/my-react-app.js:32590:12)
    at MyReactComponent.render (http://localhost:3000/my-react-app.js:125307:16)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/my-react-app.js:8292:35)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:3000/my-react-app.js:8312:33)
    at wrapper [as _renderValidatedComponent] (http://localhost:3000/my-react-app.js:2043:22)
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:3000/my-react-app.js:8265:37)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:3000/my-react-app.js:8249:11)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:3000/my-react-app.js:8178:13)
```

If I click on the forEach line, it takes me in the source to this line in the forEach function:
`baseEach(collection, baseCastFunction(iteratee));`

**Comment by motapc97** [comment]
I believe that warning comes from ImmutableJS.

**Comment by jdalton** [comment]
Our "Collection" methods check the `.length` of values provided to see if it's array like. Whoever is responsible for the warning should either reconsider or ensure it's logged only once as other libraries like Underscore and jQuery do similar checks.

**Comment by snowell** [comment]
Fair enough, however a comment made by the Immutable JS people [here](https://github.com/facebook/immutable-js/issues/543#issuecomment-121134716) makes me think it could be a problem later on.

>In a future version, this warning will be removed and code that relies on the behavior of using `length` will break.

**Comment by StreetStrider** [comment]
@snowell, this is expected for Immutable, since they encourage you to move to their full-fledged API. In the mean time, LoDash sticks to duck-typing which is more natural to JavaScript. I'm curious what's the reason you're using lodash on immutable collections? I thought they have a pretty mature and sane API with bunch of methods, don't they?

**Comment by snowell** [comment]
So they do. We were using lodash before we'd really brought in Immutable, so it's probably just a matter of somebody not knowing. Thanks, everybody!

**Comment by necronet** [comment]
I use lodash for function that immutable does not come with, like `chunk` or `partition` a solution could be to transform your immutable object back to plain JS
