### ISSUE TITLE
_.flatmap is not a function

### ISSUE THREAD

**Issue by kand617** [lodash/lodash#2101]
Hi, 

I am recieveing a strange error when invoking flatMap...

Invocation
```
var _  = require('lodash');
values = _.flatMap(products, function(p){
            return _.map(p.components,'id')
          })
``` 
Output
```
C:\Users\nzokd\Documents\Heroku\three21\server\managers\purchase-manager.js:76
          values = _.flatMap(products, function(p){
                     ^

TypeError: _.flatMap is not a function
    at Query.<anonymous> (C:\Users\nzokd\Documents\Heroku\three21\server\managers\purchase-manager.js:76:22)
    at C:\Users\nzokd\Documents\Heroku\three21\node_modules\kareem\index.js:177:19
    at C:\Users\nzokd\Documents\Heroku\three21\node_modules\kareem\index.js:109:16
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

Any ideas?
I am running `    "lodash": "^4.6.1"`

**Comment by jdalton** [comment]
Make sure your Heroku npm cache is cleared just in case and double check that `console.log(_.VERSION)` is the right one.

**Comment by kand617** [comment]
I am running this locally....
You are right, its seems to be loading 3.10.1.

**Comment by jasonkuhrt** [comment]
I ran into this same issue. In my case the context was docker. Not sure why this happened. Running a fresh `npm install` fixed it.
