### ISSUE TITLE
_.toString() doesn't work correctly in node.js

### ISSUE THREAD

**Issue by fdegiuli** [lodash/lodash#2144]
_.toString in node seems to reference `Function.prototype.toString`. 

Here's a little test file:

```
var _ = require('lodash');

console.log('1 ===========', _.toString(2));
console.log('2 ===========', _(2).toString());
console.log('3 ===========', _.map([1,2], _.toString));
```

Here's the output of `node t.js`:

```
1 =========== function lodash(value) {
      if (isObjectLike(value) && !isArray(value) && !(value instanceof LazyWrapper)) {
        if (value instanceof LodashWrapper) {
          return value;
        }
        if (hasOwnProperty.call(value, '__chain__') && hasOwnProperty.call(value, '__wrapped__')) {
          return wrapperClone(value);
        }
      }
      return new LodashWrapper(value);
    }
2 =========== 2
/Users/fdegiuli/dev/playground/node_modules/lodash/index.js:1406
        result[index] = iteratee(array[index], index, array);
                        ^
TypeError: Function.prototype.toString is not generic
    at toString (native)
    at arrayMap (/Users/fdegiuli/dev/playground/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/fdegiuli/dev/playground/node_modules/lodash/index.js:6710:14)
    at Object.<anonymous> (/Users/fdegiuli/dev/playground/t.js:5:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

It only seems to work when invoked on a wrapped value. The documentation for lodash 2.x documents this behaviour, but the newer docs seem to imply that `_.toString` should work by itself.

I've tested in every minor version of node since 0.10.0, but not in the browser.

**Comment by jdalton** [comment]
Make sure you're not in the REPL. 
> Don’t assign values to the [special variable](https://nodejs.org/api/repl.html#repl_repl_features) `_` when in the REPL.
Install [n_](https://www.npmjs.com/package/n_) for a REPL that includes lodash by default.

You can view the source of [toString](https://github.com/lodash/lodash/blob/4.6.1-npm/toString.js#L31-L44) it's simply doing `(value + '')`.
