### ISSUE TITLE
Error: No compatible version found: lodash@'>=3.7.0-0 <3.8.0-0'

### ISSUE THREAD

**Issue by bancer** [lodash/lodash#2207]
Error while running `sudo npm install -g jshint`.

```
npm http GET https://registry.npmjs.org/jshint
npm http 200 https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/jshint/-/jshint-2.9.1.tgz
npm http 200 https://registry.npmjs.org/jshint/-/jshint-2.9.1.tgz
npm http GET https://registry.npmjs.org/cli
npm http GET https://registry.npmjs.org/console-browserify
npm http GET https://registry.npmjs.org/exit
npm http GET https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/exit
npm http 200 https://registry.npmjs.org/console-browserify
npm http 200 https://registry.npmjs.org/cli
npm http 200 https://registry.npmjs.org/shelljs
npm http 200 https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/exit/-/exit-0.1.2.tgz
npm http 200 https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz
npm http 200 https://registry.npmjs.org/lodash
npm ERR! registry error parsing json
npm http 200 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/cli/-/cli-0.6.6.tgz
npm http GET https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz
npm http GET https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz
npm http GET https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz
npm ERR! Error: No compatible version found: lodash@'>=3.7.0-0 <3.8.0-0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.4.2","0.5.0-rc.1","0.5.0","0.5.1","0.5.2","0.6.0","0.6.1","0.7.0","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1","0.9.2","0.10.0","1.0.0-rc.1","1.0.0-rc.2","1.0.0-rc.3","1.0.0","1.0.1","1.1.0","1.1.1","1.2.0","1.2.1","1.3.0","1.3.1","2.0.0","2.1.0","2.2.0","2.2.1","2.3.0","2.4.0","2.4.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at next (/usr/share/npm/lib/cache.js:698:17)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-1-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "jshint"
npm ERR! cwd /home/scrutinizer/build
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 200 https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz
npm http 200 https://registry.npmjs.org/exit/-/exit-0.1.2.tgz
npm http 200 https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz
npm http 200 https://registry.npmjs.org/cli/-/cli-0.6.6.tgz
npm http 200 https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz
npm http 200 https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/scrutinizer/build/npm-debug.log
npm ERR! not ok code 0

**Comment by jdalton** [comment]
I can't repro.
