### ISSUE TITLE
Error: Cannot find module 'lodash.keys'

### ISSUE THREAD

**Issue by rosskevin** [lodash/lodash#2300]
Using a `gulpfile.babel.js` with `"gulp": "gulpjs/gulp#4.0"` latest (for everything), I get:

```javascript
$ gulp 
[11:29:29] Requiring external module babel-core/register
module.js:341
    throw err;
    ^

Error: Cannot find module 'lodash.keys'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/kross/projects/gulp-pipeline/node_modules/lodash.isequal/index.js:10:12)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kross/projects/gulp-pipeline/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

The confusing part is that inside `lodash.isequal/package.json` I see:

```javascript
  "dependencies": {
    "lodash._root": "~3.0.0",
    "lodash._stack": "~4.1.0",
    "lodash.keys": "^4.0.0"
  }
```

npm version `3.8.2`

**Comment by rosskevin** [comment]
Looks like a problem in the npm version.  Fixed by 3.8.8

`npm install -g npm && rm -Rf node_modules && npm install`
