### ISSUE TITLE
lodash crashes on require() when using node@0.10 with --harmony flag

### ISSUE THREAD

**Issue by bojand** [lodash/lodash#2324]
```
bojand@cantechlap910 lodash-test$ rm -rf node_modules/
bojand@cantechlap910 lodash-test$ nvm use 0.10
// ... npm deprecated warnings
Now using node v0.10.41 (npm v1.4.29)
bojand@cantechlap910 lodash-test$ npm i lodash
// ... npm deprecated warnings
lodash@4.12.0 node_modules/lodash
bojand@cantechlap910 lodash-test$ node --harmony
> var _ = require('lodash');
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (/Users/bojand/dev/lodash-test/node_modules/lodash/lodash.js:1143:9)
    at runInContext (/Users/bojand/dev/lodash-test/node_modules/lodash/lodash.js:4914:35)
    at Object.<anonymous> (/Users/bojand/dev/lodash-test/node_modules/lodash/lodash.js:16212:11)
    at Object.<anonymous> (/Users/bojand/dev/lodash-test/node_modules/lodash/lodash.js:16242:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
>
```

Without the `--harmony` flag it seems to work fine. `lodash@4.10` seems to work fine. `node@0.12` works fine.

**Comment by jdalton** [comment]
Thanks @bojand! `--harmony` flags enable partial, incomplete, and half-baked features. By running Node in such a way you're bound to have issues. You should also try to upgrade your Node version as it's more than 3 years old.

**Comment by NewETown** [comment]
I'm also seeing this issue running Node 6.1.0 in a Windows environment (yay Azure...)

For what it's worth it seems to run fine on a Mac/Linux. Error below:

`
D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:1143
    set.forEach(function(value) {
        ^
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:1143:9)
    at runInContext (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:4914:35)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:16212:11)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:16242:3)`

**Comment by jdalton** [comment]
Double check that Node version as `Set#forEach` exists even in 0.12:
```bash
➜  lodash-webpack-plugin git:(master) ✗ nvm use 0.12
Now using node v0.12.9 (npm v2.14.9)
➜  lodash-webpack-plugin git:(master) ✗ node
> new Set([1,2,3]).forEach(function(v) { console.log(v); });
1
2
3
```

**Comment by NewETown** [comment]
Both the package.json for my project and the server settings are set to use 6.1.0, maybe it's an issue within Sequelize?
