### ISSUE TITLE
xorBy with empty arrays

### ISSUE THREAD

**Issue by gautaz** [lodash/lodash#2333]
Hello,

Currently doing this:
```javascript
const lodash = require('lodash')
lodash.xorBy([], [{blub: 1}], (l, r) => l.blub === r.blub)
```

fails with:
```
TypeError: Cannot read property 'blub' of undefined                                                                 
    at l.xorBy (repl:1:48)
    at baseDifference (./node_modules/lodash/lodash.js:2452:35)
    at baseXor (./node_modules/lodash/lodash.js:3899:15)
    at Function.<anonymous> (./node_modules/lodash/lodash.js:7798:14)
    at Function.xorBy (./node_modules/lodash/lodash.js:10053:31)
    at repl:1:3
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
```

I would have expected that it just returns `[{blub: 1}]` as there is no element to be compared with in the left array, is that the intended behavior ?

**Comment by jdalton** [comment]
The `xyzBy` methods [provide one value to iteratees](https://lodash.com/docs#xorBy).

**Comment by gautaz** [comment]
Oups ! Sorry, misread the docs.

So there is no way to pass a comparison function ?
To be more specific, let say I want to pass the equals() method of mongodb ObjectId.

**Comment by jdalton** [comment]
See [_.xorWith](https://lodash.com/docs#xorWith).

**Comment by gautaz** [comment]
ok, I need to sleep, thanks !

**Comment by jdalton** [comment]
No problem 💤
