### ISSUE TITLE
--ignition V8 flag causes error

### ISSUE THREAD

**Issue by DJviolin** [lodash/lodash#2563]
I'm getting this error when I try to run my app with `--ignition` V8 flag:

```shell
C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:1281
    context = context ? _.defaults({}, context, _.pick(root, contextProps)) : root;
                          ^

TypeError: Cannot read property 'prototype' of undefined
    at runInContext (C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:1281:27)
    at Object.<anonymous> (C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:16580:11)
    at Object.<anonymous> (C:\www\node\lantosistvan\app\node_modules\lodash\lodash.js:16607:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

`lodash` is only installed for `gulp-uglify`:

```shell
$ npm ls lodash
lantosistvan-portfolio@1.0.0 C:\www\node\lantosistvan\app
`-- gulp-uglify@2.0.0
  `-- lodash@4.14.1
```

**Comment by jdalton** [comment]
Hi @DJviolin!

This sounds like a V8 bug. You might file it with them and link back.

**Comment by DJviolin** [comment]
Can you share with me their bug report channel?

 This one seems not the place for it: https://github.com/v8/v8/pulls

**Comment by jdalton** [comment]
Np. It's https://bugs.chromium.org/p/v8/issues/.
