### ISSUE TITLE
Cannot find module 'lodash.assign' for npm install commands

### ISSUE THREAD

**Issue by fsambou** [lodash/lodash#2577]
npm ERR! Error: no such package available : lodash.assign
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-86-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/toto/project/trunk
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by fsambou** [comment]
Installation failure was caused by "node-mocks-http@1.5.2", installation is OK with version "node-mocks-http@1.5.1"
