### ISSUE TITLE
lodashIsPlainObject breaking in Node 0.10

### ISSUE THREAD

**Issue by bcoe** [lodash/lodash#2739]
I've been working on releasing a new version of `istanbul-lib-instrument`, so that we can move the babel.js project over to [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul).

I'm running into an issue with `babel-types` on Node 0.10, which is making tests fail on Node 0.10:

```bash
istanbul-lib-instrument/node_modules/babel-types/node_modules/lodash/_setToArray.js:12
  set.forEach(function(value) {
      ^
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (/Users/benjamincoe/bcoe/istanbul-lib-instrument/node_modules/babel-types/node_modules/lodash/_setToArray.js:12:7)
    at Object.<anonymous> (/Users/benjamincoe/bcoe/istanbul-lib-instrument/node_modules/babel-types/node_modules/lodash/_createSet.js:15:31)
    at Module._compile (module.js:456:26)
    at Module.replacementCompile (/Users/benjamincoe/bcoe/istanbul-lib-instrument/node_modules/nyc/node_modules/append-transform/index.js:63:13)
    at module.exports (/Users/benjamincoe/bcoe/istanbul-lib-instrument/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/benjamincoe/bcoe/istanbul-lib-instrument/node_modules/nyc/node_modules/append-transform/index.js:67:4)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
npm ERR! Test failed.  See above for more details.
```

I've tracked the issue down to this set of changes to Lodash:

https://github.com/lodash/lodash/compare/4.11.1...4.11.2

CC: @hzoo

**Comment by bcoe** [comment]
aha! found the underlying issue. the `--harmony` flag was being set which interfered with Node 0.10 -- explains why I didn't notice this in earlier builds.

I think we can close this as will not fix 👍

**Comment by jdalton** [comment]
@bcoe Rock!

Ya the `--harmony` flag isn't supported by Lodash because it enables partial and experimental features (in other words super buggy apis).
