### ISSUE TITLE
trying to use lodash with angular2-seed

### ISSUE THREAD

**Issue by grauschnabel** [lodash/lodash#2750]
Hi there,

the angular2-seed people, where I posted this before couldn't help me, so i try it here.

Building the app for production leads to
```
[21:57:21] Starting 'build.js.prod'...

/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:479
      case 0: return func.call(thisArg);
                          ^
SyntaxError: Invalid or unexpected token
    at /home/martin/Projects/lf/client/node_modules/lodash/lodash.js:14740:16
    at apply (/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:479:27)
    at /home/martin/Projects/lf/client/node_modules/lodash/lodash.js:15124:16
    at apply (/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:481:27)
    at /home/martin/Projects/lf/client/node_modules/lodash/lodash.js:6499:16
    at template (/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:14739:20)
    at DestroyableTransform._transform (/home/martin/Projects/lf/client/node_modules/gulp-template/index.js:20:14)
    at DestroyableTransform.Transform._read (/home/martin/Projects/lf/client/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Readable.read (/home/martin/Projects/lf/client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:357:10)
    at flow (/home/martin/Projects/lf/client/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:727:26)
```
But using it with the development server there isn't any error.

Im using versions:
```
# cat package.json | grep lodash
    "@types/lodash": "^4.14.37",
    "lodash": "^4.16.4",
```

Maybe you can give me a hint, or is it a bug i lodash, this could be caught somehow I think.

Thanks,
Martin

**Comment by jdalton** [comment]
Hi @grauschnabel!

No bug that I know of. The code in the error is valid (doesn't error) so maybe it's referencing the `func` that is executed.

**Comment by CNorris724** [comment]
How was this addressed?  This randomly popped into my project and is now causing my build.prod to fail.

**Comment by coding2012** [comment]
I think it's somewhat related to this:
https://github.com/mgechev/angular-seed/issues/1612
If you're using ${ somewhere in your templates, replace it with the HTML entity &#36; instead.
