### ISSUE TITLE
'camelCase is not defined'

### ISSUE THREAD

**Issue by softfruit** [lodash/lodash#2942]
I have a dev dependency of  "lodash": "^4.17.4".

when I: ```require('lodash');```

I am receiving the error:

ReferenceError: camelCase is not defined
    at runInContext (D:\PROJECTS\REPOS\FavoritesWebsite\node_modules\lodash\lodash.js:16211:24)
    at Object.<anonymous> (D:\PROJECTS\REPOS\FavoritesWebsite\node_modules\lodash\lodash.js:16606:11)
    at Object.<anonymous> (D:\PROJECTS\REPOS\FavoritesWebsite\node_modules\lodash\lodash.js:16633:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.

if i just install camelcase and require it:
 "lodash.camelcase": "^4.3.0", >> then >>  require('lodash.camelcase');

camelcase loads fine, but requiring lodash still fails.

***

I hit this issue trying to use webpack (specifically HtmlWebpackPlugin which uses lodash) which fails as a result.

I am on:

Microsoft Windows 10 (10.0) Home 64-bit   (Build 14393) 

Below I have included my CPU-Z computer spec report. 

Regards,
Jason

http://pastebin.com/4HRz0faD

**Comment by jdalton** [comment]
Hi @softfruit!

I'm sorry but I cannot reproduce the issue. Have you tried clearing your `node_modules` folder and reinstalling?

**Comment by softfruit** [comment]
Update: 

Apparently the problem lies with Yarn 2.

Specifically with lodash it was not resolving its dependencies when installing, although vanilla npm worked fine.
