### ISSUE TITLE
Docs: Unable to collapse sections

### ISSUE THREAD

**Issue by kusold** [lodash/lodash#3004]
When trying to collapse a section on the docs, the following JS error is thrown:
```
Uncaught ReferenceError: collection is not defined
    at t.onChangeExpanded (https://lodash.com/assets/js/docs.js:1:2850)
    at i (https://lodash.com/assets/js/docs.js:1:3600)
    at D (https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.6.1,inferno@1.2.2(infer…e-class.min.js+inferno-create-element.min.js+inferno-compat.min.js:23:3760)
    at HTMLDocument.t (https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.6.1,inferno@1.2.2(infer…e-class.min.js+inferno-create-element.min.js+inferno-compat.min.js:23:4128)
onChangeExpanded @ docs.js:1
i @ docs.js:1
D @ fuse@2.6.1,inferno@1.2.2(inferno.min.js+inferno-component.min.js+inferno-create-class.min.js+infern…:23
t @ fuse@2.6.1,inferno@1.2.2(inferno.min.js+inferno-component.min.js+inferno-create-class.min.js+infern…:23
```

Reproduction steps:
1) Visit lodash.com docs
2) Attempt to collapse a section header such as "Array"

Environment:
MacOS 10.12.3
Chrome Version 56.0.2924.87 (64-bit)

**Comment by jdalton** [comment]
Thanks @kusold!

For future site bugs you can post them to [lodash/lodash.com](https://github.com/lodash/lodash.com).

**Comment by kusold** [comment]
Sorry about that. I should have looked at the repos closer. Would you like me to repost in the correct place?

**Comment by jdalton** [comment]
No need. Patched https://github.com/lodash/lodash.com/commit/513b0148ef7efa164986d9188d98f14940d40d3b.

**Comment by jdalton** [comment]
It looks like there's other visual things to work out *(a side effect of switching from Immutable.js + React to Inferno)*.
