### ISSUE TITLE
Promise.resolve is not a function in _getTag.js

### ISSUE THREAD

**Issue by kanoshin** [lodash/lodash#3208]
Hello,

I'm having this error in my app:
```
invoice:225 Unhandled rejection TypeError: Promise.resolve is not a function
    at Object.eval (http://192.168.0.64/Scripts/jspm_packages/npm/lodash@4.17.4/_getTag.js:37:32)
    at eval (http://192.168.0.64/Scripts/jspm_packages/npm/lodash@4.17.4/_getTag.js:60:4)
    at eval (http://192.168.0.64/Scripts/jspm_packages/npm/lodash@4.17.4/_getTag.js:61:3)
...
```

As far as I understand lodash can't resolve promise because I have global include of bluebird.js. 
Lodash is trying to get native Promise in _Promise.js (https://github.com/lodash/lodash/blob/4.17.4-npm/_Promise.js):
```
var Promise = getNative(root, 'Promise')
```

Why do you need exactly native one?

**Comment by jdalton** [comment]
If `Promise` isn't the built-in one then `Promise.resolve` shouldn't be reached for that bit of code since the import of `_Promise.js` should be falsey.
