### ISSUE TITLE
compact not found!

### ISSUE THREAD

**Issue by wizardnet972** [lodash/lodash#3213]
Hi,
I installed Lodash (lastest version)
Node cannot find "lodash/array/compact"

```
$ node
$ var c = require("lodash/array/compact");

Error: Cannot find module 'lodash/array/compact'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
```

Why?

**Comment by jdalton** [comment]
In Lodash v4 modules are on the package root, so `lodash/compact`.
