### ISSUE TITLE
Can not use this in _.forIn - resolves to undefined

### ISSUE THREAD

**Issue by suadhuskic** [lodash/lodash#3352]
when using `this` inside of the callback given to `_.forIn`; I get undefined.

Not sure if this is normal behavior but it sucked that I had to do destructuring for every method I wanted to call inside of the callback.

Example:
```js
const _ = require('lodash');


class Inventory {
  constructor() {
    this.required = {
      title: true,
      partNumber: true,
      description: false
    };
    this.modal = {
      title: '',
      partNumber: '',
      description: ''
    }
    this.errors = {}
  }

  //this fails.
  checkModal() {
    _.forIn(this.required, function(value, key) {
      if(value) {
        if(_.isEmpty(this.modal[key])) {
          this.appendError(key);
        }
      }
    });
  }

  //this works.
  checkModalFix() {

    const modal = this.modal;

    const appendErrorfunc = this.appendError;

    _.forIn(this.required, function(value, key) {
      if(value) {
        if(_.isEmpty(modal[key])) {
          appendErrorfunc(key);
        }
      }
    });
  }

  //this works.
  checkModalRawFix() {

    for(let prop in this.required) {
      if(this.required[prop]) {
        //its required; check value.
        if(!this.modal[prop]) {
          this.appendError(prop);
        }
      }
    }
  }


  appendError(name) {
    //append error.
    console.log(name+" is required bro!")
  }

}

const inventory = new Inventory();

//this fails.
inventory.checkModal();

//this works.
inventory.checkModalFix();

//this also works; raw javascript - using for.
inventory.checkModalRawFix();
```

If I run the code above I get:
```js
src/test.js:22
        if(_.isEmpty(this.modal[key])) {
                         ^

TypeError: Cannot read property 'modal' of undefined
    at src/test.js:22:26
    at node_modules/lodash/lodash.js:4944:15
    at Function.forIn (/node_modules/lodash/lodash.js:12938:11)
    at Inventory.checkModal (src/test.js:20:7)
    at Object.<anonymous> (src/test.js:67:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

If you comment out `inventory.checkModal();` ; it works.

**Comment by jdalton** [comment]
Hi @suadhuskic!

You should use arrow functions to preserve the outer `this` binding.

**Comment by suadhuskic** [comment]
@jdalton that was a big brain fart and maybe I'm full of them today but I replaced the function `checkModal ` above with an arrow function:
```js
  checkModal = () => {
    _.forIn(this.required, function(value, key) {
      if(value) {
        if(_.isEmpty(this.modal[key])) {
          this.appendError(key);
        }
      }
    });
  }
```

But still getting:
```js
test.js:22 Uncaught TypeError: Cannot read property 'modal' of undefined
````

No biggie bro. I will just destruct my methods.
