### ISSUE TITLE
Running enzyme-jest with latest cheerio gives lodash error: memoizeCapped is not a function

### ISSUE THREAD

**Issue by Tetheta** [lodash/lodash#3425]
I'm not convinced this is a lodash error, but I'm not getting much help from the enzyme/cheerio guys so figured I'd ask here. It's a bizarre error, cheerio is using 4.15 (tried upgrading to latest and didn't do anything) and throwing this error when I try to use it to run some tests. 

Here's the error I'm getting:

```console
Test suite failed to run

    TypeError: memoizeCapped is not a function

      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_stringToPath.js:17:20)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_castPath.js:3:20)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_baseGet.js:1:105)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/get.js:1:104)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_baseMatchesProperty.js:2:11)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/_baseIteratee.js:2:27)
      at Object.<anonymous> (node_modules/cheerio/node_modules/lodash/some.js:2:20)
      at Object.<anonymous> (node_modules/cheerio/lib/api/attributes.js:13:13)
      at Object.<anonymous> (node_modules/cheerio/lib/cheerio.js:21:3)
      at Object.<anonymous> (node_modules/cheerio/index.js:5:28)
      at Object.<anonymous> (node_modules/enzyme/build/render.js:10:16)
      at Object.<anonymous> (node_modules/enzyme/build/index.js:21:15)
      at Object.<anonymous> (node_modules/enzyme-matchers/lib/assertions/toContainReact.js:7:15)
      at Object.<anonymous> (node_modules/enzyme-matchers/lib/index.js:23:23)
      at Object.<anonymous> (node_modules/jest-enzyme/lib/index.js:5:23)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>
```
Yet the _memoizeCapped function the _stringToPath is trying to include is indeed there. Any ideas? I've tried every configuration/etc thing I can think of that would be an issue.

Jest config in package.json (probably not as relevant to you guys):
```javascript
	"jest": {
		"unmockedModulePathPatterns": [
			"react",
			"enzyme",
			"jest-enzyme"
		],
		"moduleNameMapper": {
			"\\.(jpe?g|png|gif|eot|otf|webp|svg|ttf|woff2?|mp[34]|webm|wav|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
			"\\.(css|less|s[ac]ss|styl)$": "<rootDir>/__mocks__/styleMock.js",
			"app": "<rootDir>/src/app.js"
		},
		"moduleFileExtensions": [
			"js",
			"jsx"
		],
		"moduleDirectories": [
			"src",
			"src/js",
			"node_modules"
		],
		"setupTestFrameworkScriptFile": "./node_modules/jest-enzyme/lib/index.js"
	},
```

.babelrc:
```javascript
{
	"presets": [
		[
			"env",
			{
				"modules": false,
				"targets": { "browsers": "ie >= 11, ff >= 46, > 1%" },
				"useBuiltIns": true,
				"debug": false
			}
		],
		"react"
	],
	"plugins": [
		"transform-class-properties",
		"transform-object-rest-spread"
		//'react-hot-loader/babel',
	],
	"env": {
		"test": {
			"presets": [
				"env",
				// {
				// 	"modules": false,
				// 	"targets": { "browsers": "ie >= 11, ff >= 46, > 1%" },
				// 	"useBuiltIns": true,
				// 	"debug": false
				// }
				"react"
			],
			"plugins": [
				"transform-class-properties",
                "transform-object-rest-spread",
                "transform-export-extensions"
			],
			"only": ["./**/*.js", "node_modules/jest-runtime"]
		}
	}
}
```

**Comment by jdalton** [comment]
Hi @Tetheta!

This isn't a Lodash issue. The `memoizeCapped` module is defined and is a function.
