### ISSUE TITLE
Cannot find module './_baseValue' in values.js

### ISSUE THREAD

**Issue by liangeeks** [lodash/lodash#3753]
All **`./_base*.js`** cannot found in `version: 4.17.5`

```
Error: Cannot find module './_baseValues'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liang/Workspace/kz/feedbackend/static/node_modules/webpack-merge/node_modules/lodash/values.js:1:80)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by amullier** [comment]
Hello ! What was the solution please ?

**Comment by jdalton** [comment]
The file exists so I'm guessing the error is on your end and not ours.

**Comment by Howgithub** [comment]
npm install lodash
