### ISSUE TITLE
Deprecation warnings from crypto

### ISSUE THREAD

**Issue by pillpack-raisch** [lodash/lodash#4324]
Lodash version: 4.17.11
Node version: 10.13.3

When I `require('lodash')` in the context of my bespoke utils package, it emits to console:

```
(node:16017) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:16017) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:16017) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```

which is strange because as far as I can tell lodash does not use crypto.

Full trace:
```
(node:16128) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
    at .../node_modules/lodash/lodash.js:4911:32
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
    at baseMergeDeep (.../node_modules/lodash/lodash.js:3695:9)
    at .../node_modules/lodash/lodash.js:3609:11
    at .../node_modules/lodash/lodash.js:4911:15
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
    at baseMergeDeep (.../node_modules/lodash/lodash.js:3695:9)
    at .../node_modules/lodash/lodash.js:3609:11
    at .../node_modules/lodash/lodash.js:4911:15
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
(node:16128) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
    at .../node_modules/lodash/lodash.js:4911:32
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
    at baseMergeDeep (.../node_modules/lodash/lodash.js:3695:9)
    at .../node_modules/lodash/lodash.js:3609:11
    at .../node_modules/lodash/lodash.js:4911:15
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
    at baseMergeDeep (.../node_modules/lodash/lodash.js:3695:9)
    at .../node_modules/lodash/lodash.js:3609:11
    at .../node_modules/lodash/lodash.js:4911:15
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
(node:16128) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
    at .../node_modules/lodash/lodash.js:4911:32
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
    at baseMergeDeep (.../node_modules/lodash/lodash.js:3695:9)
    at .../node_modules/lodash/lodash.js:3609:11
    at .../node_modules/lodash/lodash.js:4911:15
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
    at baseMergeDeep (.../node_modules/lodash/lodash.js:3695:9)
    at .../node_modules/lodash/lodash.js:3609:11
    at .../node_modules/lodash/lodash.js:4911:15
    at baseMerge (.../node_modules/lodash/lodash.js:3606:7)
```

**Comment by falsyvalues** [comment]
Hi @pillpack-raisch!
It's node internal warning not related to lodash. See node [deprecations](https://nodejs.org/api/deprecations.html#deprecations_dep0011_crypto_credentials).
