### ISSUE TITLE
webpack build vue project

### ISSUE THREAD

**Issue by p2ng** [lodash/lodash#4363]
my project is vue
- env
  - node 12.6.0
  - "lodash": "^4.17.14"

- error
`npm run build`

```

> soeasycenter-portal@1.0.0 build:prod /Users/liangzp/Document/source/soeasycenter/soeasycenter-portal
> cross-env NODE_ENV=production env_config=prod node build/build.js

⠼ building for production...Error processing file: static/css/app.a5c1c0da5bff9cc20d799edbfea2c514.css
(node:11871) UnhandledPromiseRejectionWarning: CssSyntaxError: /Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/static/css/app.a5c1c0da5bff9cc20d799edbfea2c514.css:1197:3: Unknown word
    at Input.error (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/parser.js:563:22)
    at Parser.decl (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/parser.js:235:16)
    at Parser.other (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/parser.js:133:18)
    at Parser.parse (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/parser.js:77:16)
    at parse (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/processor.js:117:23)
    at Function.creator.process (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/postcss.js:148:43)
    at OptimizeCssAssetsPlugin.processCss (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/index.js:63:19)
    at Object.processor (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/optimize-css-assets-webpack-plugin/index.js:29:23)
    at /Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/last-call-webpack-plugin/index.js:139:8
    at arrayEach (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/lodash/forEach.js:38:10)
    at LastCallWebpackPlugin.process (/Users/liangzp/Document/source/soeasycenter/soeasycenter-portal/node_modules/last-call-webpack-plugin/index.js:136:3)
(node:11871) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Xotic750** [comment]
I don't think this is lodash related. However, too little information to be more helpful than:

https://www.google.com/search?ei=vqkoXezBFO7yqwGHpqD4DA&q=CssSyntaxError+unknown+word&oq=CssSyntaxError+unknown+word&gs_l=psy-ab.3..0i19l3j0i22i30i19l2.1495.4997..5252...0.0..0.274.1963.6j2j5......0....1..gws-wiz.......0i10i30i19j0i30i19.29ZHa103L7U
