### ISSUE TITLE
lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null

### ISSUE THREAD

**Issue by stephaniewilkinson** [lodash/lodash#4377]
Hi! I am trying to update lodash-es from 4.17.11 to 4.17.14 and am getting an error when I bump the version. Any help would be appreciated! Thank you!

```
$ ember test
Building
Environment: test
cleaning up
cleaning up...
Build Error (broccoli-persistent-filter:Babel > [Babel: lodash]) in lodash/org.js

lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
```

```
ERROR Summary:

- broccoliBuilderErrorStack: TypeError: lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
at Object.validate (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-types/lib/definitions/index.js:109:13)
at Object.validate (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-types/lib/index.js:505:9)
at NodePath._replaceWith (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/replacement.js:176:7)
at NodePath._remove (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/removal.js:58:10)
at NodePath.remove (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/removal.js:30:8)
at PluginPass.CallExpression (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:42:12)
at NodePath._call (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/context.js:48:17)
at NodePath.visit (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/context.js:105:12)
at TraversalContext.visitQueue (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/context.js:150:16)
- code: [undefined]
- codeFrame: lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
- errorMessage: lodash/org.js: lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
in /tmp/broccoli-6111aM6LX3n6LpZR/out-367-funnel_funnel_addon_js
at broccoli-persistent-filter:Babel > [Babel: lodash] (Babel: lodash)
- errorType: Build Error
- location:
- column: [undefined]
- file: lodash/org.js
- line: [undefined]
- treeDir: /tmp/broccoli-6111aM6LX3n6LpZR/out-367-funnel_funnel_addon_js
- message: lodash/org.js: lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
in /tmp/broccoli-6111aM6LX3n6LpZR/out-367-funnel_funnel_addon_js
at broccoli-persistent-filter:Babel > [Babel: lodash] (Babel: lodash)
- name: BuildError
- nodeAnnotation: Babel: lodash
- nodeName: broccoli-persistent-filter:Babel > [Babel: lodash]
- originalErrorMessage: lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
- stack: TypeError: lodash/org.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
at Object.validate (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-types/lib/definitions/index.js:109:13)
at Object.validate (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-types/lib/index.js:505:9)
at NodePath._replaceWith (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/replacement.js:176:7)
at NodePath._remove (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/removal.js:58:10)
at NodePath.remove (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/removal.js:30:8)
at PluginPass.CallExpression (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:42:12)
at NodePath._call (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/context.js:48:17)
at NodePath.visit (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/path/context.js:105:12)
at TraversalContext.visitQueue (/home/rof/src/github.com/NAISorg/market-view-ui/node_modules/babel-traverse/lib/context.js:150:16)

=================================================================================

error Command failed with exit code 1.
```

**Comment by jdalton** [comment]
Thanks @stephaniewilkinson!

I bumped the packages to remove the unintentionally added helpers.

**Comment by stephaniewilkinson** [comment]
Fantastic! Thanks for the quick response. I'll try again.

**Comment by nateperry** [comment]
I too have been having this exact issue. @jdalton can you give a little more context to what happened and what the solution was? I understand that a later version fixed this, just trying to get a better sense of what it was.

**Comment by jdalton** [comment]
This has been resolved with the `lodash` package collection (`lodash, `lodash-amd`, and `lodash-es`) update to `4.17.15`. The problem was package-organization/repo-tag helper scripts I use accidentally got added to the npm publish packages. Updating your dep will resolve the issue.

**Comment by nateperry** [comment]
Thanks for the details! I can confirm that I am no longer seeing this error.
