### ISSUE TITLE
What's the status of package.json?

### ISSUE THREAD

**Issue by ip1981** [lodash/lodash#4484]
It looks dated, `npm run build`, `npm test` do not work:

```
$ npm test
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> lodash@5.0.0 pretest /home/pashev/tmp/lodash
> npm run build

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> lodash@5.0.0 build /home/pashev/tmp/lodash
> npm run build:main && npm run build:fp

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> lodash@5.0.0 build:main /home/pashev/tmp/lodash
> node lib/main/build-dist.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pashev/tmp/lodash/lib/main/build-dist.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 build:main: `node lib/main/build-dist.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lodash@5.0.0 build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pashev/.npm/_logs/2019-09-26T09_59_27_123Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodash@5.0.0 build: `npm run build:main && npm run build:fp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lodash@5.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pashev/.npm/_logs/2019-09-26T09_59_27_231Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by falsyvalues** [comment]
Hi @ip1981!
Take a look on [CONTRIBUTING.md](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#construction-notice-construction) notice, since master is under work things may not work.

**Comment by albedoa** [comment]
fyi I found this thread through a google search after some head-scratching. As I was not exploring the code for contribution reasons, I did not think to check that link!
