### ISSUE TITLE
DeprecationWarning: process.binding() is deprecated

### ISSUE THREAD

**Issue by OAFCROB** [lodash/lodash#4851]
# Bug report

*Receiving node deprecation warning for [process.binding()](https://nodejs.org/api/deprecations.html#deprecations_dep0111_process_binding) from usage of lodash in webpack*

Apologises if this has already been raised but we're currently receiving the following error in our logs every time we hit out Lambdas, when we have the node options to show the pending deprecation warnings. 

`NODE_OPTIONS: "--trace-warnings --pending-deprecation"` 

```
ERROR	(node:8) [DEP0111] DeprecationWarning: process.binding() is deprecated. Please use public APIs instead.
    at /var/task/src/handlers/webpack:/node_modules/lodash/_nodeUtil.js:26:62
    at Object.<anonymous> (/var/task/src/handlers/webpack:/node_modules/lodash/_nodeUtil.js:16:16)
    at Object.call (/var/task/src/handlers/index.js:1030:16134)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
    at Object.call (/var/task/src/handlers/webpack:/node_modules/lodash/isTypedArray.js:3:16)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
    at Object.call (/var/task/src/handlers/webpack:/node_modules/lodash/_arrayLikeKeys.js:6:20)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
    at Object.call (/var/task/src/handlers/webpack:/node_modules/lodash/keys.js:1:21)
    at r (/var/task/src/handlers/webpack:/webpack/bootstrap:19:22)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Enable pending deprecation warnings and trace warnings for node
`NODE_OPTIONS: "--trace-warnings --pending-deprecation"` 

**What is the expected behavior?**
No deprecation warnings for node 10+

**Other relevant information:**
Node.js version: nodejs12.x

**Comment by falsyvalues** [comment]
Hi @OAFCROB!

This code is quite old but contains checks for version 10+ so it should not generate warnings.

```js
  var nodeUtil = (function() {
    try {
      // Use `util.types` for Node.js 10+.
      var types = freeModule && freeModule.require && freeModule.require('util').types;

      if (types) {
        return types;
      }

      // Legacy `process.binding('util')` for Node.js < 10.
      return freeProcess && freeProcess.binding && freeProcess.binding('util');
    } catch (e) {}
  }());
```

**Comment by OAFCROB** [comment]
@falsyvalues yeah saw that, not sure what's generating these warnings. We've turned off the node_option for now and planning on having another look at in the new year. It could be some other package causing the issue but until we find out what's the root cause, I would be happy for this to be closed. We can always re-open it if we do find an issue. Thanks for help anyway.
