### ISSUE TITLE
Warning: Accessing non-existent property 'Symbol(Symbol.toStringTag)' of module exports inside circular dependency

### ISSUE THREAD

**Issue by TheoMer** [lodash/lodash#5072]
OS: Windows 10 Pro
Node: 14.15.4
ts-node-dev: 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 3.9.7)
Lodash: 4.17.20

I'm receiving the following error warning when doing `npm run dev':

```
(node:14820) Warning: Accessing non-existent property 'Symbol(Symbol.toStringTag)' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.toString (<anonymous>)
    at objectToString (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\_objectToString.js:19:31)
    at baseGetTag (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\_baseGetTag.js:25:7)
    at baseClone (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\_baseClone.js:112:15)
    at clone (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\clone.js:33:10)
    at Object.<anonymous> (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\cloudinary\lib\v2\index.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\ts-node-dev\node_modules\source-map-support\source-map-support.js:547:25)
(node:14820) Warning: Accessing non-existent property 'length' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at isArrayLike (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\isArrayLike.js:30:42)
    at keys (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\keys.js:34:10)
    at baseAssign (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\_baseAssign.js:14:39)
    at baseClone (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\_baseClone.js:123:32)
    at clone (C:\Users\d0475\Documents\Projects\flamingo-ecom2\sick-fits\backend\node_modules\lodash\clone.js:33:10)
```

What is the issue here?

**Comment by 1xtr** [comment]
I waiting too )
