### ISSUE TITLE
lodash-es@4.17.15: maximum call stack size exceeded when compiling

### ISSUE THREAD

**Issue by jpike88** [lodash/lodash#5074]
```- RangeError: Maximum call stack size exceeded
    at findResolutionCycleStartIndex (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:50232:21)
    at pushTypeResolution (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:50216:45)
    at getTypeOfVariableOrParameterOrPropertyWorker (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:51063:18)
    at getTypeOfVariableOrParameterOrProperty (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:51020:28)
    at getTypeOfSymbol (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:51353:24)
    at checkIdentifier (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:64406:49)
    at checkExpressionWorker (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:71921:28)
    at checkExpression (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:71870:38)
    at checkNonNullExpression (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:66943:37)
    at checkPropertyAccessExpression (/home/ec2-user/environment/wtf/node_modules/typescript/lib/typescript.js:66988:85)```

typescript@4.1.3 is freaking out when trying to build Lodash-es@4.17.5 to an es5 target.

**Comment by Mersall** [comment]
any update  ??
