### ISSUE TITLE
Some tests are not running by npm test

### ISSUE THREAD

**Issue by rluvaton** [lodash/lodash#5136]
There are test files in the test directory that aren't been run by the `test` script (those test files don't end with `.test.js` only `.js`

https://github.com/lodash/lodash/blob/2f79053d7bc7c9c9561a30dda202b3dcd2b72b90/package.json#L13

### List Files
```
test/Arrays-category-methods.js
test/ary.js
test/assign-and-assignIn.js
test/assignIn.js
test/assignInWith.js
test/assignWith-and-assignInWith.js
test/basename.js
test/before.js
test/bind.js
test/bindAll.js
test/bindKey.js
test/chain.js
test/clamp.js
test/clone-methods.js
test/compact.js
test/concat.js
test/cond.js
test/conforms-methods.js
test/conforms.js
test/constant.js
test/countBy.js
test/curry-methods.js
test/curry.js
test/curryRight.js
test/custom-_.iteratee-methods.js
test/debounce-and-throttle.js
test/defaultsDeep.js
test/delay.js
test/difference-methods.js
test/differenceBy.js
test/dropRightWhile.js
test/dropWhile.js
test/every.js
test/exit-early.js
test/extremum-methods.js
test/fill.js
test/filter-methods.js
test/find-and-findLast.js
test/find-and-includes.js
test/find-methods.js
test/flatMap-methods.js
test/flatMapDepth.js
test/flatten-methods.js
test/flattenDepth.js
test/forIn-methods.js
test/forOwn-methods.js
test/fromPairs.js
test/get-and-result.js
test/groupBy.js
test/has-methods.js
test/head.js
test/identity.js
test/includes.js
test/indexOf-methods.js
test/initial.js
test/inRange.js
test/intersection-methods.js
test/intersectionBy.js
test/invertBy.js
test/invoke.js
test/invokeMap.js
test/isArray.js
test/isEmpty.js
test/isEqual.js
test/isEqualWith.js
test/isFinite.js
test/isFunction.js
test/isInteger-methods.js
test/isIterateeCall.js
test/isMatchWith.js
test/isNaN.js
test/isNative.js
test/isPlainObject.js
test/isType-checks.js
test/isTypedArray.js
test/iteratee.js
test/iteration-methods.js
test/join.js
test/keyBy.js
test/keys-methods.js
test/last.js
test/lodash(...)-methods-that-return-new-wrapped-values.js
test/lodash(...)-methods-that-return-the-wrapped-modified-array.js
test/lodash(...)-methods-that-return-unwrapped-values.js
test/lodash(...).commit.js
test/lodash(...).next.js
test/lodash(...).plant.js
test/lodash(...).pop.js
test/lodash(...).push.js
test/lodash(...).shift.js
test/lodash(...).sort.js
test/lodash(...).splice.js
test/lodash(...).unshift.js
test/lodash(...).value.js
test/lodash-constructor.js
test/lodash-methods.js
test/lodash.methodName.js
test/map-caches.js
test/map.js
test/mapKeys-and-mapValues.js
test/mapKeys.js
test/mapValues.js
test/matches-methods.js
test/matches.js
test/matchesProperty.js
test/math-operator-methods.js
test/max.js
test/meanBy.js
test/mergeWith.js
test/method.js
test/methodOf.js
test/methods-using-createWrapper.js
test/min.js
test/mixin.js
test/negate.js
test/noConflict.js
test/now.js
test/nth.js
test/nthArg.js
test/number-coercion-methods.js
test/object-assignments.js
test/omit-methods.js
test/omit.js
test/omitBy.js
test/orderBy.js
test/over.js
test/overArgs.js
test/overEvery.js
test/overSome.js
test/pad-methods.js
test/pad.js
test/padEnd.js
test/padStart.js
test/parseInt.js
test/partial-methods.js
test/partialRight.js
test/partition.js
test/pick-methods.js
test/pick.js
test/pull-methods.js
test/pullAt.js
test/random.js
test/range-methods.js
test/rearg.js
test/reduce-methods.js
test/reduce.js
test/reduceRight.js
test/remove.js
test/repeat.js
test/rest.js
test/reverse.js
test/round-methods.js
test/runInContext.js
test/sample.js
test/sampleSize.js
test/set-methods.js
test/setWith.js
test/shuffle.js
test/slice-and-toArray.js
test/slice.js
test/some.js
test/sortBy-methods.js
test/sortBy.js
test/sortedIndex-methods.js
test/sortedIndexBy-methods.js
test/sortedIndexOf-methods.js
test/split.js
test/spread.js
test/startsWith-and-endsWith.js
test/startsWith.js
test/strict-mode-checks.js
test/stub-methods.js
test/sum-methods.js
test/sumBy.js
test/tail.js
test/take.js
test/takeRight.js
test/takeRightWhile.js
test/takeWhile.js
test/tap.js
test/template.js
test/throttle.js
test/times.js
test/toInteger-methods.js
test/toLower.js
test/toPairs-methods.js
test/toPairs.js
test/toPairsIn.js
test/toPath.js
test/toPlainObject.js
test/toUpper.js
test/transform.js
test/trim-methods.js
test/truncate.js
test/unary.js
test/uncommon-symbols.js
test/unescape.js
test/union-methods.js
test/unionBy.js
test/uniq-methods.js
test/uniq.js
test/uniqBy-methods.js
test/unset.js
test/unzip-and-zip.js
test/unzipWith.js
test/update-methods.js
test/updateWith.js
test/utils.js
test/values-methods.js
test/wrap.js
test/xor-methods.js
test/xorBy.js
test/zipObject-methods.js
test/zipWith.js
test/__proto__-property-bugs.js
```

**Comment by VijayKumarHP** [comment]
++ could anyone suggest on the below issue why it's not running npm tests?
[root]# npm test

> lodash@4.17.21 test /root/apic/lodash
> echo "See https://travis-ci.org/lodash-archive/lodash-cli for testing details."

See https://travis-ci.org/lodash-archive/lodash-cli for testing details.

**Comment by rluvaton** [comment]
Pinging...

**Comment by liwzhang** [comment]
I tried testing isEqual.js and it fails 4 of the tests, I'm wondering if this is the reason?

```
1) isEqual
       should compare array views:
     ReferenceError: root is not defined
      at /home/ezhang/lodash/test/isEqual.test.js:401:32
      at baseTimes (node_modules/lodash/lodash.js:976:23)
      at Proxy.times (node_modules/lodash/lodash.js:16171:20)
      at Context.<anonymous> (test/isEqual.test.js:400:18)
      at processImmediate (internal/timers.js:464:21)

  2) isEqual
       should compare error objects:
     ReferenceError: root is not defined
      at /home/ezhang/lodash/test/isEqual.test.js:454:19
      at arrayMap (node_modules/lodash/lodash.js:639:23)
      at Proxy.map (node_modules/lodash/lodash.js:9580:14)
      at Context.<anonymous> (test/isEqual.test.js:444:30)
      at processImmediate (internal/timers.js:464:21)

  3) isEqual
       should compare sets:
     ReferenceError: Cannot access 'convert' before initialization
      at equalByTag (.internal/equalByTag.js:83:7)
      at baseIsEqualDeep (.internal/baseIsEqualDeep.js:58:9)
      at baseIsEqual (.internal/baseIsEqual.js:25:10)
      at isEqual (eqDeep.js:30:10)
      at /home/ezhang/lodash/test/isEqual.test.js:547:28
      at arrayEach (node_modules/lodash/lodash.js:516:11)
      at Proxy.forEach (node_modules/lodash/lodash.js:9368:14)
      at Context.<anonymous> (test/isEqual.test.js:541:20)
      at processImmediate (internal/timers.js:464:21)

  4) isEqual
       should compare sets with circular references:
     ReferenceError: Cannot access 'convert' before initialization
      at equalByTag (.internal/equalByTag.js:83:7)
      at baseIsEqualDeep (.internal/baseIsEqualDeep.js:58:9)
      at baseIsEqual (.internal/baseIsEqual.js:25:10)
      at isEqual (eqDeep.js:30:10)
      at Context.<anonymous> (test/isEqual.test.js:573:26)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by Sunny-117** [comment]
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/73089592/210543517-49939f24-aab8-4a1a-aaa5-2fade17118a1.png">
after i change file from differenceBy.js to differenceBy.test.js , then, it has error

**Comment by Sunny-117** [comment]
TypeError: iteratee is not a function

**Comment by Sunny-117** [comment]
actual = differenceBy([{ 'x': 2 }, { 'x': 1 }], [{ 'x': 1 }], 'x');

this case
