### ISSUE TITLE
camelCase of lodash not working.

### ISSUE THREAD

**Issue by evolvingg** [lodash/lodash#5591]
camelCase is not working for me.

Here's how am using it

import camelCase from 'lodash/camelCase';
console.log(camelCase("hello world"));

I also tried using
import { camelCase } from 'lodash';

both ways of importing didnt work. Dont know whats wrong here.
<img width="1440" alt="Screenshot 2023-01-22 at 8 42 28 PM" src="https://user-images.githubusercontent.com/7952016/213923600-2315b8c6-9070-44b0-bf61-f6e6c8b076f4.png">

**Comment by matusekma** [comment]
HI @evolvingg ,
try using require() instead. You are probably using CommonJS modules.
```
const { camelCase } = require('lodash');  
camelCase('hello world')
```

**Comment by evolvingg** [comment]
Hi @matusekma , thanks for replying, was using es6 import.
Here's uniq method which worked fine, however for camelCase method i get the error.

import uniq from 'lodash/uniq';
import camelCase from 'lodash/camelCase';

const numbers = [1, 5, 8, 10, 1, 5, 15, 42, 5];
console.log(camelCase("hello world"));
console.log(uniq(numbers));


using webpack for bundling, package.json has dev dependencies - 

    "webpack": "^5.75.0",
    "webpack-bundle-analyzer": "^4.7.0",
    "webpack-cli": "^5.0.1"

**Comment by j-koziel** [comment]
A bit late to the party but have you set the "type" option to "module" in package.json

like this...
`
{
"type": "module"
}
`

**Comment by evolvingg** [comment]
@j-koziel , didnt work for me i even tried changing syntax of webpack.config.js

Failed to load '/Users/iavanish/Documents/myApp/webpack.config.js' config
[webpack-cli] ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/iavanish/Documents/myApp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/iavanish/Documents/myApp/webpack.config.js:1:14
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async WebpackCLI.tryRequireThenImport (/Users/iavanish/Documents/myApp/node_modules/webpack-cli/lib/webpack-cli.js:225:26)
    at async loadConfigByPath (/Users/iavanish/Documents/myApp/node_modules/webpack-cli/lib/webpack-cli.js:1325:27)
    at async WebpackCLI.loadConfig (/Users/iavanish/Documents/myApp/node_modules/webpack-cli/lib/webpack-cli.js:1431:38)
    at async WebpackCLI.createCompiler (/Users/iavanish/Documents/myApp/node_modules/webpack-cli/lib/webpack-cli.js:1643:22)
    at async Command.<anonymous> (/Users/iavanish/Documents/myApp/node_modules/@webpack-cli/serve/lib/index.js:82:30)

**Comment by j-koziel** [comment]
yeah when you set the type to module in package.json that means you can use es modules... so instead of require use the import syntax you were using before

**Comment by j-koziel** [comment]
@evolvingg any progress?
