### ISSUE TITLE
I updated to React 18 recently and my react app is not longer running and it's related to lodash

### ISSUE THREAD

**Issue by nnha19** [lodash/lodash#5598]
**Note** : I have `lodash@4.17.21` installed

As far as I have checked, we are not using lodash anywhere in our project. But, I think some libs we are using internally use lodash. I tried deleting `node_modules` and `package-lock.json` more than 5 times and there was no improement. This is the error message in the console

```
Uncaught Error: Cannot find module 'lodash/debounce'
    at webpackMissingModule (index.js:83:1)
    at ./node_modules/@tiptap/extension-bubble-menu/dist/index.js (index.js:83:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@tiptap/react/dist/index.js (index.js:1:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

This is the warning in the console

```
ERROR in ./node_modules/@tiptap/extension-bubble-menu/dist/index.js 7:0-39
Module not found: Error: Can't resolve 'lodash/debounce' in 'node_modules\@tiptap\extension-bubble-menu\dist'
Did you mean 'debounce.js'?
BREAKING CHANGE: The request 'lodash/debounce' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

It seems like there is conflict with **lodash** and  **@tiptap\extension-bubble-menu**. What is happening and how do I solve this issue? I checked my **package.json**  file and we don't even have `@tiptap\extension-bubble-menu` package installed. We have other packages installed from `@tiptap` though. These could be related

```
"@tiptap/extension-table": "^2.0.0-beta.209",
    "@tiptap/extension-table-cell": "^2.0.0-beta.209",
    "@tiptap/extension-table-header": "^2.0.0-beta.209",
    "@tiptap/extension-table-row": "^2.0.0-beta.209",
    "@tiptap/prosemirror-tables": "^1.1.4",
    "@tiptap/react": "^2.0.0-beta.209",
    "@tiptap/starter-kit": "^2.0.0-beta.209",
```

**Comment by rafde** [comment]
@nnha19 you can try using https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
