### ISSUE TITLE
Lodash Clonedeep cache issue.

### ISSUE THREAD

**Issue by subhroacharjee** [lodash/lodash#5631]
# Issue
In typescript 4.8, i have been building a feature that would take nested custom file object array and then deep cloning the whole array to prevent write operation on the real objects
```typescript
export type Files = File[];
  addFiles(...files: Files) {
    const queue = _.cloneDeep(files);
    while (queue.length !== 0) {
      const node = queue.pop()!
      if ("files" in node) {
        queue.push(...node.files())
      } else {
        this.addFile(node)
      }
    }
  }
```
So after cloning 12 such arrays the cloneDeep function threw the following error.
```stack
[2023-04-14T16:53:12.200] [ERROR] default - /home/subhro/work/cdk/node_modules/lodash/lodash.js:2249
      data.set(key, value);
           ^

[2023-04-14T16:53:12.203] [ERROR] default - RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at MapCache.mapCacheSet [as set] (/home/subhro/work/cdk/node_modules/lodash/lodash.js:2249:12)
    at Stack.stackSet [as set] (/home/subhro/work/cdk/node_modules/lodash/lodash.js:2403:12)
    at baseClone (/home/subhro/work/cdk/node_modules/lodash/lodash.js:2710:13)
    at /home/subhro/work/cdk/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/home/subhro/work/cdk/node_modules/lodash/lodash.js:530:11)
    at baseClone (/home/subhro/work/cdk/node_modules/lodash/lodash.js:2727:7)
    at /home/subhro/work/cdk/node_modules/lodash/lodash.js:2733:34
    at arrayEach (/home/subhro/work/cdk/node_modules/lodash/lodash.js:530:11)
```

As much as i understand the issue is with caching data in clonedeep function. This has also caused heap memory out issue in the system and also slowed down the parent function.

**Comment by anmol242** [comment]
Raised a PR for fix, https://github.com/lodash/lodash/pull/5647
