### ISSUE TITLE
TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<WeakMap>'

### ISSUE THREAD

**Issue by sainnhe** [lodash/lodash#5871]
Hi, thanks for your work. I'm using a nodejs based application named coc-explorer, which is a vim extension, but I encountered a bug:

```log
2024-05-27T22:24:39.197 ERROR (pid:115475) [extension-stat] - Error on parse json file /home/sainnhe/.local/share/nvim/coc/extensions/package.json TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<WeakMap>'
    at getRawTag (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:6127:27)
    at baseGetTag (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:6159:64)
    at Object.<anonymous> (/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:7314:292)
    at Module.<anonymous> (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:77963:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at Object.sandboxRequire [as require] (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:78002:42)
    at createExtension (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:78035:33)
```

It seems to be a bug of lodash, since the content of `/home/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-explorer/lib/index.js:6127:27` is as follows:

```js
// node_modules/lodash-es/_getRawTag.js
var objectProto = Object.prototype;
var hasOwnProperty = objectProto.hasOwnProperty;
var nativeObjectToString = objectProto.toString;
var symToStringTag = Symbol_default ? Symbol_default.toStringTag : void 0;
function getRawTag(value) {
  var isOwn = hasOwnProperty.call(value, symToStringTag), tag = value[symToStringTag];
  try {
    value[symToStringTag] = void 0;
    var unmasked = true;
  } catch (e2) {
  }
  var result = nativeObjectToString.call(value);
  if (unmasked) {
    if (isOwn) {
      value[symToStringTag] = tag;
    } else {
      delete value[symToStringTag];
    }
  }
  return result;
}
var getRawTag_default = getRawTag;
```

Could you have a look at this bug? Thanks!

For more information https://github.com/weirongxu/coc-explorer/issues/584

**Comment by sainnhe** [comment]
I can confirm that this bug is caused by line:

```js
value[symToStringTag] = void 0;
```

The source code is located in tag [4.17.21-es](https://github.com/lodash/lodash/tree/4.17.21-es)

https://github.com/lodash/lodash/blob/11eb817cdfacf56c02d7005cbe520ffbeb0fe59a/_getRawTag.js#L26-L44

Seems like this property is read-only and cannot be altered.

**Comment by sainnhe** [comment]
After some investigations, I find that this bug seems to be caused by fedora linux package (I'm using `nodejs` package and the version is 20.12.2). The code is placed in a try-catch statement and should be catched by node, but it didn't.

I tried the official binary release on nodejs website and this issue doesn't exist.

**Comment by sainnhe** [comment]
Confirmed this is a packaging issue in fedora. Closed.

**Comment by helllamer** [comment]
Sorry for necro-posting , just notes for myself and other unluckies:

This packaging time-eating issue still nearby, now on ArchlinuxARM (RaspberryPI 4, ARM64).

Tried:
- `nodejs-23.7.0-aarch64`
- `nodejs-lts-jod-22.13.1-aarch64`
-  `nodejs-lts-iron-20.18.2-aarch64`

all current builds are affected:

```
$ yay -S immich-server
...
vite v6.0.11 building SSR bundle for production...
...
node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<WeakMap>'
    at getRawTag (file:///home/alarm/immich/immich/src/immich-1.126.1/web/node_modules/lodash-es/_getRawTag.js:31:27)
    at baseGetTag (file:///home/alarm/immich/immich/src/immich-1.126.1/web/node_modules/lodash-es/_baseGetTag.js:24:7)
    at file:///home/alarm/immich/immich/src/immich-1.126.1/web/node_modules/lodash-es/_getTag.js:39:17
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async Promise.all (index 0)
    at async analyse (file:///home/alarm/immich/immich/src/immich-1.126.1/web/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:74:16)
    at async MessagePort.<anonymous> (file:///home/alarm/immich/immich/src/immich-1.126.1/web/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)
```

Resolved using [official nodejs builds](https://nodejs.org/en/download/current):
```
wget https://nodejs.org/dist/v23.7.0/node-v23.7.0-linux-arm64.tar.xz
tar xf node-v23.7.0-linux-arm64.tar.xz
mv node-v23.7.0-linux-arm64/bin/node /bin/node
```
