### ISSUE TITLE
`cloneArrayBuffer` Outputs Node Deprecation Warning

### ISSUE THREAD

**Issue by hhanesand** [lodash/lodash#5923]
Hello! It seems the `arrayBuffer.constructor` line in `cloneArrayBuffer` is causing a Node deprecation warning.

What should be done about this? I assume the library is choosing to use this `.constructor` syntax to keep support custom subclasses?

```
(node:59189) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:188:11)
    at new Buffer (node:buffer:266:3)
    at cloneArrayBuffer (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_cloneTypedArray.js:16:16)
    at assignMergeValue (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseMergeDeep.js:94:16)
    at keysIn (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseMerge.js:42:16)
    at <anonymous> (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_createBaseFor.js:25:16)
    at keysIn (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseMerge.js:42:16)
    at assignMergeValue (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseMergeDeep.js:94:16)
    at keysIn (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseMerge.js:42:16)
    at <anonymous> (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_createBaseFor.js:25:16)
    at keysIn (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseMerge.js:42:16)
    at baseMerge (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/merge.js:39:16)
    at isIterateeCall (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_createAssigner.js:37:16)
    at apply (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_apply.js:21:16)
    at apply (/Users/hhanesand/Developer/Enode/vendor-service/common/temp/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_overRest.js:36:16)
    at setDefaults (/Users/hhanesand/Developer/Enode/vendor-service/packages/private-shared/src/lib/axios.ts:416:33)
```

**Comment by hhanesand** [comment]
Here's a workaround:

```
mergeWith(...., (_, srcValue) => {
  if (srcValue instanceof Buffer) {
    return srcValue;
  }

  return undefined;
})
```
