### ISSUE TITLE
syntax error on line 260 in lodash.js

### ISSUE THREAD

**Issue by bazo** [lodash/lodash#862]
lodash 2.4.1

**Comment by geekflyer** [comment]
please copy the code of the mentioned line and some lines around it in here

**Comment by geekflyer** [comment]
and also please tell in which browser / environment you're attempting to run this

**Comment by bazo** [comment]
node.js. lodash is installed as a dependency of some gulp package. when i run a gulp task, i get this error message

/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/lodash/dist/lodash.js:260
});
 ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/lib/findup-sync.js:16:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by geekflyer** [comment]
Could you attach the lodash.js file here maybe?

In any case, you can copy the contents of lodash dist from here https://raw.githubusercontent.com/lodash/lodash/2.4.1/dist/lodash.js into your clipboard and replace it with the existing content. I would be heavily surprised if that doesn't fix the problem.

**Comment by geekflyer** [comment]
also you should do once `npm cache clean` . Probably the lodash module downloaded by your client got corrupted somehow.

**Comment by jdalton** [comment]
I'm guessing corrupt download as Lo-Dash don't have a syntax error otherwise.
