### ISSUE TITLE
Function.isPlainObject fails when using ES6

### ISSUE THREAD

**Issue by gsklee** [lodash/lodash#981]
```
[00:42:29] TypeError: boolean is not a function
    at Function.isPlainObject (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/dist/lodash.js:1652:64)
    at Object.globule.find (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:64:19)
    at Gaze.add (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:174:19)
    at new Gaze (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/home/kaylee/projects/manic/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/home/kaylee/projects/manic/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/home/kaylee/projects/manic/gulpfile.babel.js:85:10)
    at module.exports (/home/kaylee/projects/manic/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/kaylee/projects/manic/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

Related issues: https://github.com/babel/babel/issues/489, https://github.com/wearefractal/glob-watcher/issues/15

**Comment by jdalton** [comment]
Not sure what the issue is. It looks like it's using lodash v2.4.1. We have an es6 build for v3 that is compiled with 6to5 without issue. Might ping https://github.com/cowboy/node-globule/issues.

**Comment by jdalton** [comment]
The [line number](https://github.com/lodash/lodash/blob/2.4.1/dist/lodash.js#L1652) in the error isn't very helpful either.

**Comment by jdalton** [comment]
Found the issue outlined [here](https://github.com/babel/babel/issues/489#issuecomment-69919417):
> Looks like it's a result of gulp depending on vinyl-fs that depends on glob-watcher that uses an outdated version of gaze which uses an outdated version of globule that uses an oudated version of lodash that has a dodgy Object.getPrototypeOf check because core-js overrides it.

[core-js](https://github.com/zloirock/core-js) is the root cause because it wraps `Object.getPrototypeOf` and causes issues.

**Comment by gsklee** [comment]
Okay, thanks.

**Comment by jdalton** [comment]
fwiw lodash correctly detects `_.isNative(Object.getPrototypeOf)` as `false`.
See http://jsbin.com/pugimomame/1/.

**Comment by sebmck** [comment]
@jdalton It's actually using v1.0.1 and the cause of the issue is as I described [here](https://github.com/babel/babel/issues/489#issuecomment-75186394). The latest version of `globule` does indeed use lodash v2.4.1 but not the old version which is being used.

**Comment by jdalton** [comment]
Rock @sebmck, thanks for taking the time to investigate.
