### ISSUE TITLE
_.curry() can't be used in a map

### ISSUE THREAD

**Issue by callumacrae** [lodash/lodash#998]
I have the following code:

```js
_(fs.readdirSync(dirPath))
  .map(_.curry(path.join, 2)(dirPath))
```

In theory, it should return the full paths of all the files in `dirPath`. Instead, it throws an error:

```
path.js:471
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
    at posix.join (path.js:471:13)
    at wrapper (/Users/callumacrae/Sites/find-node-modules-down/node_modules/lodash/index.js:3165:85)
    at Object.<anonymous> (/Users/callumacrae/Sites/find-node-modules-down/index.js:9:41)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

This seems to be because of the extra argument provided by `.map()`. The same error can be replicated by the following:

```js
_.curry(path.join, 2)('one')('two', 1)
```

In my opinion, if the arity is specified, that number—and _only_ that number—of arguments should be given to the function.

```js
_.curry(path.join, 2)('one')('two', 1) //=> path.join('one', 'two')
```

I can't think of any cases where this would break stuff, and it would be useful for currying functions for maps and stuff. Would you accept a PR fixing this functionality?

**Comment by jdalton** [comment]
You can use [_.ary](https://lodash.com/docs#ary) to cap the arg limit of a function:
```js
_.curry(_.ary(path.join, 2), 2);
```

**Comment by callumacrae** [comment]
:+1: that works
